// Generated by Kukicha (requires Go 1.27+)

package archive

import (
	"archive/tar"
	"archive/zip"
	"compress/gzip"
	"errors"
	"fmt"
	"io"
	kukistring "kukicha.org/kukicha/stdlib/string"
	"os"
	"path/filepath"
	"time"
)

type Entry struct {
	Name    string
	Size    int64
	Mode    os.FileMode
	ModTime time.Time
	IsDir   bool
}

const defaultMaxExtractBytes = 2147483648

func Extract(archivePath string, dest string) error {
	return ExtractLimit(archivePath, dest, defaultMaxExtractBytes)
}

func ExtractLimit(archivePath string, dest string, maxBytes int64) error {
	if maxBytes <= 0 {
		return fmt.Errorf("archive: extract limit must be positive, got %v", maxBytes)
	}
	format := detectFormat(archivePath)
	if format == "zip" {
		return extractZip(archivePath, dest, maxBytes)
	}
	if format == "targz" {
		return extractTarGz(archivePath, dest, maxBytes)
	}
	return fmt.Errorf("archive: unrecognized format for %v (want .zip, .tar.gz, or .tgz)", archivePath)
}

func List(archivePath string) ([]Entry, error) {
	format := detectFormat(archivePath)
	if format == "zip" {
		return listZip(archivePath)
	}
	if format == "targz" {
		return listTarGz(archivePath)
	}
	return nil, fmt.Errorf("archive: unrecognized format for %v", archivePath)
}

func ReadEntry(archivePath string, name string) ([]byte, error) {
	format := detectFormat(archivePath)
	if format == "zip" {
		return readEntryZip(archivePath, name)
	}
	if format == "targz" {
		return readEntryTarGz(archivePath, name)
	}
	return nil, fmt.Errorf("archive: unrecognized format for %v", archivePath)
}

var ErrEntryNotFound = errors.New("archive: entry not found")

func ReadEntryOr(archivePath string, name string, defaultValue []byte) ([]byte, error) {
	data, err := ReadEntry(archivePath, name)
	if err == nil {
		return data, nil
	}
	if errors.Is(err, ErrEntryNotFound) {
		return defaultValue, nil
	}
	return nil, err
}

func EntryExists(archivePath string, name string) bool {
	format := detectFormat(archivePath)
	if format == "zip" {
		r, err_1 := zip.OpenReader(archivePath)
		if err_1 != nil {
			return false
		}
		defer r.Close()
		_, err := r.Reader.Open(name)
		return err == nil
	}
	if format == "targz" {
		return tarGzHasEntry(archivePath, name)
	}
	return false
}

func tarGzHasEntry(archivePath string, name string) bool {
	f, err_2 := os.Open(archivePath)
	if err_2 != nil {
		return false
	}
	defer f.Close()
	gz, err_3 := gzip.NewReader(f)
	if err_3 != nil {
		return false
	}
	defer gz.Close()
	tr := tar.NewReader(gz)
	for {
		hdr, hdrErr := tr.Next()
		if errors.Is(hdrErr, io.EOF) {
			return false
		}
		if hdrErr != nil {
			return false
		}
		if hdr.Name == name {
			return true
		}
	}
}

func ExtractEntry(archivePath string, name string, dest string) error {
	format := detectFormat(archivePath)
	if format == "zip" {
		return extractEntryZip(archivePath, name, dest)
	}
	if format == "targz" {
		return extractEntryTarGz(archivePath, name, dest)
	}
	return fmt.Errorf("archive: unrecognized format for %v", archivePath)
}

func WriteZip(archivePath string, paths []string) error {
	for _, p := range paths {
		if filepath.IsAbs(p) {
			return fmt.Errorf("archive: absolute paths not allowed in WriteZip: %v", p)
		}
		if !filepath.IsLocal(p) {
			return fmt.Errorf("archive: path escapes source directory in WriteZip: %v", p)
		}
	}
	out, err_4 := os.Create(archivePath)
	if err_4 != nil {
		return err_4
	}
	defer out.Close()
	zw := zip.NewWriter(out)
	defer zw.Close()
	for _, p := range paths {
		info, err_5 := os.Stat(p)
		if err_5 != nil {
			return err_5
		}
		if info.IsDir() {
			return fmt.Errorf("archive: WriteZip does not recurse directories (%v); use WriteTarGz for directory trees", p)
		}
		hdr, err_6 := zip.FileInfoHeader(info)
		if err_6 != nil {
			return err_6
		}
		hdr.Name = filepath.ToSlash(p)
		hdr.Method = zip.Deflate
		w, err_7 := zw.CreateHeader(hdr)
		if err_7 != nil {
			return err_7
		}
		src, err_8 := os.Open(p)
		if err_8 != nil {
			return err_8
		}
		_, copyErr := io.Copy(w, src)
		err_9 := src.Close()
		if err_9 != nil {
			return err_9
		}
		if copyErr != nil {
			return copyErr
		}
	}
	return nil
}

func WriteTarGz(archivePath string, sourceDir string) error {
	info, err_10 := os.Stat(sourceDir)
	if err_10 != nil {
		return err_10
	}
	if !info.IsDir() {
		return fmt.Errorf("archive: WriteTarGz source must be a directory: %v", sourceDir)
	}
	out, err_11 := os.Create(archivePath)
	if err_11 != nil {
		return err_11
	}
	defer out.Close()
	gw := gzip.NewWriter(out)
	defer gw.Close()
	tw := tar.NewWriter(gw)
	defer tw.Close()
	return writeTarDir(tw, sourceDir, sourceDir)
}

func detectFormat(path string) string {
	lower := kukistring.ToLower(path)
	if kukistring.HasSuffix(lower, ".zip") {
		return "zip"
	}
	if kukistring.HasSuffix(lower, ".tar.gz") || kukistring.HasSuffix(lower, ".tgz") {
		return "targz"
	}
	return ""
}

func safeJoin(dest string, name string) (string, error) {
	if !filepath.IsLocal(name) {
		return "", fmt.Errorf("archive: entry escapes destination: %v", name)
	}
	target := filepath.Join(dest, name)
	parent := filepath.Dir(target)
	if parent != "." && parent != "/" {
		current := parent
		for current != "." && current != "/" && len(current) != 0 {
			info, statErr := os.Lstat(current)
			if statErr == nil && info.Mode()&os.ModeSymlink != 0 {
				return "", fmt.Errorf("archive: destination symlink detected at %v: entry %v", current, name)
			}
			current = filepath.Dir(current)
		}
	}
	checkPath := target
	for len(checkPath) != 0 {
		info, statErr := os.Lstat(checkPath)
		if statErr == nil && info != nil && info.Mode()&os.ModeSymlink != 0 {
			return "", fmt.Errorf("archive: symlink in destination path: %v (entry %v)", checkPath, name)
		}
		checkPath = filepath.Dir(checkPath)
		if checkPath == "." || checkPath == "/" {
			break
		}
	}
	return target, nil
}

func copyCapped(dst io.Writer, src io.Reader, remaining int64) (int64, error) {
	limited := io.LimitReader(src, remaining+1)
	written, err_12 := io.Copy(dst, limited)
	if err_12 != nil {
		return 0, err_12
	}
	if written > remaining {
		return written, errors.New("archive: extracted size exceeds limit")
	}
	return written, nil
}

func extractZip(archivePath string, dest string, maxBytes int64) error {
	err_13 := os.MkdirAll(dest, 0o755)
	if err_13 != nil {
		return err_13
	}
	r, err_14 := zip.OpenReader(archivePath)
	if err_14 != nil {
		return err_14
	}
	defer func() {
		_ = r.Close()
	}()
	remaining := maxBytes
	var closeErr error
	for _, f := range r.File {
		if !filepath.IsLocal(f.Name) {
			return fmt.Errorf("archive: entry escapes destination: %v", f.Name)
		}
		target, err_15 := safeJoin(dest, f.Name)
		if err_15 != nil {
			return err_15
		}
		if f.FileInfo().IsDir() {
			err_16 := os.MkdirAll(target, f.Mode().Perm())
			if err_16 != nil {
				return err_16
			}
			continue
		}
		err_17 := os.MkdirAll(filepath.Dir(target), 0o755)
		if err_17 != nil {
			return err_17
		}
		rc, err_18 := f.Open()
		if err_18 != nil {
			return err_18
		}
		outFile, openErr := os.OpenFile(target, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, f.Mode().Perm())
		if openErr != nil {
			err_19 := rc.Close()
			if err_19 != nil {
				return err_19
			}
			return fmt.Errorf("archive: open failed for %v", f.Name)
		}
		written, copyErr := copyCapped(outFile, rc, remaining)
		rcCloseErr := rc.Close()
		fileCloseErr := outFile.Close()
		if rcCloseErr != nil && closeErr == nil {
			closeErr = rcCloseErr
		}
		if fileCloseErr != nil && closeErr == nil {
			closeErr = fmt.Errorf("archive: close error for %v", f.Name)
		}
		if copyErr != nil {
			return copyErr
		}
		remaining = remaining - written
	}
	rCloseErr := r.Close()
	if rCloseErr != nil && closeErr == nil {
		closeErr = rCloseErr
	}
	if closeErr != nil {
		return closeErr
	}
	return nil
}

func extractTarGz(archivePath string, dest string, maxBytes int64) error {
	err_20 := os.MkdirAll(dest, 0o755)
	if err_20 != nil {
		return err_20
	}
	f, err_21 := os.Open(archivePath)
	if err_21 != nil {
		return err_21
	}
	defer func() {
		_ = f.Close()
	}()
	gz, err_22 := gzip.NewReader(f)
	if err_22 != nil {
		return err_22
	}
	defer func() {
		_ = gz.Close()
	}()
	tr := tar.NewReader(gz)
	remaining := maxBytes
	var closeErr error
	for {
		hdr, hdrErr := tr.Next()
		if errors.Is(hdrErr, io.EOF) {
			break
		}
		if hdrErr != nil {
			return hdrErr
		}
		if !filepath.IsLocal(hdr.Name) {
			return fmt.Errorf("archive: entry escapes destination: %v", hdr.Name)
		}
		target, err_23 := safeJoin(dest, hdr.Name)
		if err_23 != nil {
			return err_23
		}
		if hdr.Typeflag == tar.TypeDir {
			err_24 := os.MkdirAll(target, hdr.FileInfo().Mode().Perm())
			if err_24 != nil {
				return err_24
			}
			continue
		}
		if hdr.Typeflag != tar.TypeReg {
			continue
		}
		err_25 := os.MkdirAll(filepath.Dir(target), 0o755)
		if err_25 != nil {
			return err_25
		}
		outFile, openErr := os.OpenFile(target, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, hdr.FileInfo().Mode().Perm())
		if openErr != nil {
			return fmt.Errorf("archive: open failed for %v", hdr.Name)
		}
		written, copyErr := copyCapped(outFile, tr, remaining)
		fileCloseErr := outFile.Close()
		if fileCloseErr != nil && closeErr == nil {
			closeErr = fmt.Errorf("archive: close error for %v", hdr.Name)
		}
		if copyErr != nil {
			return copyErr
		}
		remaining = remaining - written
	}
	fCloseErr := f.Close()
	gzCloseErr := gz.Close()
	if fCloseErr != nil && closeErr == nil {
		closeErr = fCloseErr
	}
	if gzCloseErr != nil && closeErr == nil {
		closeErr = gzCloseErr
	}
	if closeErr != nil {
		return closeErr
	}
	return nil
}

func listZip(archivePath string) ([]Entry, error) {
	r, err_26 := zip.OpenReader(archivePath)
	if err_26 != nil {
		return []Entry{}, err_26
	}
	defer r.Close()
	entries := []Entry{}
	for _, f := range r.File {
		info := f.FileInfo()
		entries = append(entries, Entry{Name: f.Name, Size: info.Size(), Mode: info.Mode(), ModTime: info.ModTime(), IsDir: info.IsDir()})
	}
	return entries, nil
}

func listTarGz(archivePath string) ([]Entry, error) {
	f, err_27 := os.Open(archivePath)
	if err_27 != nil {
		return []Entry{}, err_27
	}
	defer f.Close()
	gz, err_28 := gzip.NewReader(f)
	if err_28 != nil {
		return []Entry{}, err_28
	}
	defer gz.Close()
	tr := tar.NewReader(gz)
	entries := []Entry{}
	for {
		hdr, hdrErr := tr.Next()
		if errors.Is(hdrErr, io.EOF) {
			break
		}
		if hdrErr != nil {
			return nil, hdrErr
		}
		fi := hdr.FileInfo()
		entries = append(entries, Entry{Name: hdr.Name, Size: hdr.Size, Mode: fi.Mode(), ModTime: hdr.ModTime, IsDir: fi.IsDir()})
	}
	return entries, nil
}

func readEntryZip(archivePath string, name string) ([]byte, error) {
	r, err_29 := zip.OpenReader(archivePath)
	if err_29 != nil {
		return []byte{}, err_29
	}
	defer r.Close()
	for _, f := range r.File {
		if f.Name == name {
			if f.FileInfo().IsDir() {
				return nil, fmt.Errorf("archive: entry is a directory: %v", name)
			}
			rc, err_30 := f.Open()
			if err_30 != nil {
				return []byte{}, err_30
			}
			defer rc.Close()
			return io.ReadAll(rc)
		}
	}
	return nil, fmt.Errorf("%w: %v", ErrEntryNotFound, name)
}

func readEntryTarGz(archivePath string, name string) ([]byte, error) {
	f, err_31 := os.Open(archivePath)
	if err_31 != nil {
		return []byte{}, err_31
	}
	defer f.Close()
	gz, err_32 := gzip.NewReader(f)
	if err_32 != nil {
		return []byte{}, err_32
	}
	defer gz.Close()
	tr := tar.NewReader(gz)
	for {
		hdr, hdrErr := tr.Next()
		if errors.Is(hdrErr, io.EOF) {
			break
		}
		if hdrErr != nil {
			return nil, hdrErr
		}
		if hdr.Name == name {
			if hdr.FileInfo().IsDir() {
				return nil, fmt.Errorf("archive: entry is a directory: %v", name)
			}
			return io.ReadAll(tr)
		}
	}
	return nil, fmt.Errorf("%w: %v", ErrEntryNotFound, name)
}

func extractEntryZip(archivePath string, name string, dest string) error {
	if !filepath.IsLocal(name) {
		return fmt.Errorf("archive: entry escapes destination: %v", name)
	}
	r, err_33 := zip.OpenReader(archivePath)
	if err_33 != nil {
		return err_33
	}
	defer r.Close()
	for _, f := range r.File {
		if f.Name == name {
			if f.FileInfo().IsDir() {
				return fmt.Errorf("archive: entry is a directory: %v", name)
			}
			rc, err_34 := f.Open()
			if err_34 != nil {
				return err_34
			}
			defer rc.Close()
			target, joinErr := safeJoin(dest, name)
			if joinErr != nil {
				return joinErr
			}
			err_35 := os.MkdirAll(filepath.Dir(target), 0o755)
			if err_35 != nil {
				return err_35
			}
			outFile, createErr := os.OpenFile(target, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, f.FileInfo().Mode().Perm())
			if createErr != nil {
				return fmt.Errorf("archive: open failed for %v", name)
			}
			_, copyErr := copyCapped(outFile, rc, defaultMaxExtractBytes)
			closeErr := outFile.Close()
			if copyErr != nil {
				return copyErr
			}
			if closeErr != nil {
				return fmt.Errorf("archive: close error for %v", name)
			}
			return nil
		}
	}
	return fmt.Errorf("%w: %v", ErrEntryNotFound, name)
}

func extractEntryTarGz(archivePath string, name string, dest string) error {
	if !filepath.IsLocal(name) {
		return fmt.Errorf("archive: entry escapes destination: %v", name)
	}
	f, err_36 := os.Open(archivePath)
	if err_36 != nil {
		return err_36
	}
	defer f.Close()
	gz, err_37 := gzip.NewReader(f)
	if err_37 != nil {
		return err_37
	}
	defer gz.Close()
	tr := tar.NewReader(gz)
	for {
		hdr, hdrErr := tr.Next()
		if errors.Is(hdrErr, io.EOF) {
			return fmt.Errorf("%w: %v", ErrEntryNotFound, name)
		}
		if hdrErr != nil {
			return hdrErr
		}
		if hdr.Name == name {
			if hdr.FileInfo().IsDir() {
				return fmt.Errorf("archive: entry is a directory: %v", name)
			}
			target, joinErr := safeJoin(dest, name)
			if joinErr != nil {
				return joinErr
			}
			err_38 := os.MkdirAll(filepath.Dir(target), 0o755)
			if err_38 != nil {
				return err_38
			}
			outFile, createErr := os.OpenFile(target, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, hdr.FileInfo().Mode().Perm())
			if createErr != nil {
				return fmt.Errorf("archive: open failed for %v", name)
			}
			_, copyErr := copyCapped(outFile, tr, defaultMaxExtractBytes)
			closeErr := outFile.Close()
			if copyErr != nil {
				return copyErr
			}
			if closeErr != nil {
				return fmt.Errorf("archive: close error for %v", name)
			}
			return nil
		}
	}
}

func writeTarDir(tw *tar.Writer, root string, dir string) error {
	entries, err_39 := os.ReadDir(dir)
	if err_39 != nil {
		return err_39
	}
	for _, e := range entries {
		full := filepath.Join(dir, e.Name())
		info, err_40 := e.Info()
		if err_40 != nil {
			return err_40
		}
		rel, err_41 := filepath.Rel(root, full)
		if err_41 != nil {
			return err_41
		}
		hdr, err_42 := tar.FileInfoHeader(info, "")
		if err_42 != nil {
			return err_42
		}
		hdr.Name = filepath.ToSlash(rel)
		err_43 := tw.WriteHeader(hdr)
		if err_43 != nil {
			return err_43
		}
		if info.IsDir() {
			err_44 := writeTarDir(tw, root, full)
			if err_44 != nil {
				return err_44
			}
			continue
		}
		if !info.Mode().IsRegular() {
			continue
		}
		src, err_45 := os.Open(full)
		if err_45 != nil {
			return err_45
		}
		_, copyErr := io.Copy(tw, src)
		err_46 := src.Close()
		if err_46 != nil {
			return err_46
		}
		if copyErr != nil {
			return copyErr
		}
	}
	return nil
}
