// Generated by Kukicha (requires Go 1.27+)

package era

import (
	"fmt"
	ctxpkg "kukicha.org/kukicha/stdlib/ctx"
	"kukicha.org/kukicha/stdlib/files"
	"kukicha.org/kukicha/stdlib/llm/safe"
	"kukicha.org/kukicha/stdlib/parse"
	"kukicha.org/kukicha/stdlib/shell"
	"kukicha.org/kukicha/stdlib/sort"
	strpkg "kukicha.org/kukicha/stdlib/string"
	"math"
	"math/rand"
)

const DefaultExploration = 1.4142135623730951

const RecombinationProbability = 0.25

const DefaultTopK = 3

const MaxBlockBytes = 16384

type Task struct {
	Description string
	Baseline    string
	Higher      bool
	Ideas       []string
}

type Candidate struct {
	Source string
	Score  float64
	Parent int
	Valid  bool
	Visits int
}

func Run(h ctxpkg.Handle, ask func(string) (string, error), task Task, score func(string) (float64, error), budget int) (Candidate, []Candidate, error) {
	tree := []Candidate{}
	rootScore, rootErr := score(task.Baseline)
	root := Candidate{Source: task.Baseline, Score: rootScore, Parent: -1, Valid: rootErr == nil, Visits: 0}
	tree = append(tree, root)
	for range budget {
		if h.Ctx.Err() != nil {
			break
		}
		parentIdx := SelectFUTS(tree, task.Higher, DefaultExploration)
		if parentIdx < 0 {
			break
		}
		useRecombine := countValid(tree) >= DefaultTopK && rand.Float64() < RecombinationProbability
		var proposal string
		var proposeErr error
		if useRecombine {
			proposal, proposeErr = ProposeRecombination(ask, task, topK(tree, task.Higher, DefaultTopK))
		} else {
			proposal, proposeErr = ProposeRewrite(ask, task, tree[parentIdx], best(tree, task.Higher))
		}
		tree[parentIdx].Visits = tree[parentIdx].Visits + 1
		if proposeErr != nil {
			continue
		}
		candScore, candErr := score(proposal)
		candParent := func() int {
			if useRecombine {
				return -1
			} else {
				return parentIdx
			}
		}()
		cand := Candidate{Source: proposal, Score: candScore, Parent: candParent, Valid: candErr == nil, Visits: 0}
		tree = append(tree, cand)
	}
	return best(tree, task.Higher), tree, nil
}

func SelectFUTS(tree []Candidate, higher bool, exploration float64) int {
	if len(tree) == 0 {
		return -1
	}
	totalVisits := 0
	validCount := 0
	for _, c := range tree {
		if c.Valid {
			validCount = validCount + 1
			totalVisits = totalVisits + c.Visits + 1
		}
	}
	if validCount == 0 {
		return -1
	}
	lo, hi := minMaxValidScore(tree)
	span := hi - lo
	if span == 0.0 {
		span = 1.0
	}
	bestIdx := -1
	bestUCB := math.Inf(-1)
	for idx := range len(tree) {
		c := tree[idx]
		if !c.Valid {
			continue
		}
		norm := (c.Score - lo) / span
		if !higher {
			norm = 1.0 - norm
		}
		ucb := norm + exploration*math.Sqrt(math.Log(float64(totalVisits))/float64(c.Visits+1))
		if ucb > bestUCB {
			bestUCB = ucb
			bestIdx = idx
		}
	}
	return bestIdx
}

func ProposeRewrite(ask func(string) (string, error), task Task, parent Candidate, best Candidate) (string, error) {
	direction := func() string {
		if task.Higher {
			return "MAXIMIZE"
		} else {
			return "MINIMIZE"
		}
	}()
	instructions := fmt.Sprintf("You are improving a piece of source code to %v a numeric score.\nProblem: %v\nParent score: %v\nCurrent best score: %v\nReturn ONLY the complete new source. No prose, explanations, or markdown fences.", direction, task.Description, parent.Score, best.Score)
	blocks := []string{safe.Wrap("PARENT_SOURCE", safe.Truncate(parent.Source, MaxBlockBytes))}
	if len(task.Ideas) != 0 {
		ideas := safe.Truncate(strpkg.Join(task.Ideas, "\n---\n"), MaxBlockBytes)
		blocks = append(blocks, safe.Wrap("IDEAS", ideas))
	}
	prompt := safe.Frame(instructions, blocks)
	raw, err_1 := ask(prompt)
	if err_1 != nil {
		return "", err_1
	}
	return stripFences(raw), nil
}

func ProposeRecombination(ask func(string) (string, error), task Task, top []Candidate) (string, error) {
	direction := func() string {
		if task.Higher {
			return "MAXIMIZE"
		} else {
			return "MINIMIZE"
		}
	}()
	instructions := fmt.Sprintf("Synthesize a hybrid source that combines the strongest aspects of the candidates below to %v the score.\nProblem: %v\nReturn ONLY the complete new source. No prose, explanations, or markdown fences.", direction, task.Description)
	blocks := []string{}
	for i := range len(top) {
		c := top[i]
		label := fmt.Sprintf("CANDIDATE_%v_SCORE_%v", i+1, c.Score)
		blocks = append(blocks, safe.Wrap(label, safe.Truncate(c.Source, MaxBlockBytes)))
	}
	if len(task.Ideas) != 0 {
		ideas := safe.Truncate(strpkg.Join(task.Ideas, "\n---\n"), MaxBlockBytes)
		blocks = append(blocks, safe.Wrap("IDEAS", ideas))
	}
	prompt := safe.Frame(instructions, blocks)
	raw, err_2 := ask(prompt)
	if err_2 != nil {
		return "", err_2
	}
	return stripFences(raw), nil
}

func BuildScore(source string) (float64, error) {
	dir, cleanup, dirErr := files.TempDirAuto("era-build-")
	if dirErr != nil {
		return 0.0, dirErr
	}
	defer cleanup()
	path := files.Join(dir, "candidate.kuki")
	err_3 := files.WriteString(path, source)
	if err_3 != nil {
		return 0, err_3
	}
	shell.Output("kukicha", "build", "--json", "--skip-build", path)
	return 1.0, nil
}

func RunScore(source string, metric func(string) (float64, error)) (float64, error) {
	dir, cleanup, dirErr := files.TempDirAuto("era-run-")
	if dirErr != nil {
		return 0.0, dirErr
	}
	defer cleanup()
	path := files.Join(dir, "candidate.kuki")
	err_4 := files.WriteString(path, source)
	if err_4 != nil {
		return 0, err_4
	}
	out, err_5 := shell.Output("kukicha", "run", path)
	if err_5 != nil {
		return 0, err_5
	}
	return metric(out)
}

func BenchScore(source string, setup func(string) (string, error), benchName string) (float64, error) {
	workDir, err_6 := setup(source)
	if err_6 != nil {
		return 0, err_6
	}
	// pipe step 1: Output(...)
	out, err_8 := shell.New("go", "test", "-bench", benchName, "-benchmem", "-count=1", "-run=^$", "./...").Dir(workDir).Output()
	if err_8 != nil {
		return 0, err_8
	}
	return parseBenchNsPerOp(out, benchName)
}

func StripFences(s string) string {
	return stripFences(s)
}

func stripFences(s string) string {
	s = strpkg.TrimSpace(s)
	if !strpkg.HasPrefix(s, "```") {
		return s
	}
	lines := strpkg.Split(s, "\n")
	if len(lines) < 2 {
		return s
	}
	lines = lines[1:]
	if len(lines) != 0 && strpkg.HasPrefix(lines[len(lines)-1], "```") {
		lines = lines[:len(lines)-1]
	}
	return strpkg.TrimSpace(strpkg.Join(lines, "\n"))
}

func countValid(tree []Candidate) int {
	n := 0
	for _, c := range tree {
		if c.Valid {
			n = n + 1
		}
	}
	return n
}

func minMaxValidScore(tree []Candidate) (float64, float64) {
	lo := math.Inf(1)
	hi := math.Inf(-1)
	for _, c := range tree {
		if !c.Valid {
			continue
		}
		if c.Score < lo {
			lo = c.Score
		}
		if c.Score > hi {
			hi = c.Score
		}
	}
	return lo, hi
}

func best(tree []Candidate, higher bool) Candidate {
	var bestC Candidate
	found := false
	for _, c := range tree {
		if !c.Valid {
			continue
		}
		if !found {
			bestC = c
			found = true
			continue
		}
		if higher && c.Score > bestC.Score {
			bestC = c
		}
		if !higher && c.Score < bestC.Score {
			bestC = c
		}
	}
	return bestC
}

func topK(tree []Candidate, higher bool, k int) []Candidate {
	valid := []Candidate{}
	for _, c := range tree {
		if c.Valid {
			valid = append(valid, c)
		}
	}
	valid = sort.By(valid, func(a Candidate, b Candidate) bool {
		return func() bool {
			if higher {
				return a.Score > b.Score
			} else {
				return a.Score < b.Score
			}
		}()
	})
	if len(valid) > k {
		valid = valid[:k]
	}
	return valid
}

func parseBenchNsPerOp(out string, benchName string) (float64, error) {
	prefix := fmt.Sprintf("Benchmark%v", benchName)
	for _, line := range strpkg.Lines(out) {
		if !strpkg.HasPrefix(line, prefix) {
			continue
		}
		fields := strpkg.Fields(line)
		for i := range len(fields) {
			if fields[i] == "ns/op" && i > 0 {
				return parse.Float64(fields[i-1])
			}
		}
	}
	return 0.0, fmt.Errorf("no benchmark line matched %v", benchName)
}
