// Generated by Kukicha (requires Go 1.27+)

package set_test

import (
	"kukicha.org/kukicha/stdlib/iterator"
	"kukicha.org/kukicha/stdlib/set"
	"kukicha.org/kukicha/stdlib/slice"
	kukistring "kukicha.org/kukicha/stdlib/string"
	"kukicha.org/kukicha/stdlib/test"
	"testing"
)

func TestNew(t *testing.T) {
	t.Run("creates empty set", func(t *testing.T) {
		s := set.New[string]()
		test.AssertEqual(t, set.Len(s), 0)
		test.AssertTrue(t, set.IsEmpty(s))
	})
	t.Run("can add items after creation", func(t *testing.T) {
		s := set.New[string]()
		set.Add(s, "a")
		test.AssertEqual(t, set.Len(s), 1)
		test.AssertTrue(t, set.Contains(s, "a"))
	})
}

type FromCase struct {
	name    string
	input   []string
	wantLen int
}

func TestFrom(t *testing.T) {
	cases := []FromCase{FromCase{name: "empty", input: []string{}, wantLen: 0}, FromCase{name: "three unique", input: []string{"a", "b", "c"}, wantLen: 3}, FromCase{name: "duplicates deduplicated", input: []string{"a", "a", "b"}, wantLen: 2}}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			s := set.From[string](tc.input)
			test.AssertEqual(t, set.Len(s), tc.wantLen)
		})
	}
}

type AddCase struct {
	name    string
	item    string
	wantLen int
}

func TestAdd(t *testing.T) {
	cases := []AddCase{AddCase{name: "new item", item: "c", wantLen: 3}, AddCase{name: "existing item", item: "a", wantLen: 2}}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			s := set.From[string]([]string{"a", "b"})
			set.Add(s, tc.item)
			test.AssertEqual(t, set.Len(s), tc.wantLen)
		})
	}
}

func TestInsertAll(t *testing.T) {
	t.Run("accumulates into an existing set", func(t *testing.T) {
		s := set.From[string]([]string{"a"})
		set.InsertAll(s, []string{"b", "c", "a"})
		test.AssertEqual(t, set.Len(s), 3)
		test.AssertTrue(t, set.ContainsAll(s, []string{"a", "b", "c"}))
	})
	t.Run("empty list is a no-op", func(t *testing.T) {
		s := set.From[string]([]string{"x"})
		set.InsertAll(s, []string{})
		test.AssertEqual(t, set.Len(s), 1)
	})
	t.Run("into a fresh set", func(t *testing.T) {
		s := set.New[int]()
		set.InsertAll(s, []int{1, 2, 2, 3})
		test.AssertEqual(t, set.Len(s), 3)
	})
}

func TestRemove(t *testing.T) {
	t.Run("existing item", func(t *testing.T) {
		s := set.From[string]([]string{"a", "b", "c"})
		set.Remove(s, "b")
		test.AssertEqual(t, set.Len(s), 2)
		test.AssertFalse(t, set.Contains(s, "b"))
	})
	t.Run("missing item is no-op", func(t *testing.T) {
		s := set.From[string]([]string{"a"})
		set.Remove(s, "z")
		test.AssertEqual(t, set.Len(s), 1)
	})
	t.Run("idempotent", func(t *testing.T) {
		s := set.From[string]([]string{"a", "b"})
		set.Remove(s, "b")
		set.Remove(s, "b")
		test.AssertEqual(t, set.Len(s), 1)
	})
}

func TestContains(t *testing.T) {
	s := set.From[string]([]string{"x", "y"})
	t.Run("present", func(t *testing.T) {
		test.AssertTrue(t, set.Contains(s, "x"))
	})
	t.Run("absent", func(t *testing.T) {
		test.AssertFalse(t, set.Contains(s, "z"))
	})
}

func TestContainsAll(t *testing.T) {
	s := set.From[string]([]string{"a", "b", "c"})
	t.Run("all present", func(t *testing.T) {
		test.AssertTrue(t, set.ContainsAll(s, []string{"a", "c"}))
	})
	t.Run("missing one", func(t *testing.T) {
		test.AssertFalse(t, set.ContainsAll(s, []string{"a", "z"}))
	})
	t.Run("empty list is contained in every set", func(t *testing.T) {
		fresh := set.New[string]()
		test.AssertTrue(t, set.ContainsAll(fresh, []string{}))
		test.AssertTrue(t, set.ContainsAll(s, []string{}))
	})
	t.Run("non-empty list is not contained in empty", func(t *testing.T) {
		fresh := set.New[string]()
		test.AssertFalse(t, set.ContainsAll(fresh, []string{"a"}))
	})
}

func TestToSlice(t *testing.T) {
	s := set.From[string]([]string{"a", "b", "c"})
	items := set.ToList(s)
	test.AssertEqual(t, len(items), 3)
	t.Run("contains all elements", func(t *testing.T) {
		test.AssertTrue(t, slice.Contains(items, "a"))
		test.AssertTrue(t, slice.Contains(items, "b"))
		test.AssertTrue(t, slice.Contains(items, "c"))
	})
	t.Run("Has and Size aliases", func(t *testing.T) {
		test.AssertTrue(t, set.Has(s, "a"))
		test.AssertFalse(t, set.Has(s, "z"))
		test.AssertEqual(t, set.Size(s), 3)
	})
}

func TestToSortedList(t *testing.T) {
	t.Run("ints ascend", func(t *testing.T) {
		s := set.From[int]([]int{3, 1, 2, 3})
		test.AssertEqual(t, set.ToSortedList(s), []int{1, 2, 3})
	})
	t.Run("strings ascend", func(t *testing.T) {
		s := set.From[string]([]string{"pear", "apple", "fig"})
		test.AssertEqual(t, set.ToSortedList(s), []string{"apple", "fig", "pear"})
	})
	t.Run("empty yields empty", func(t *testing.T) {
		fresh := set.New[string]()
		test.AssertTrue(t, len(set.ToSortedList(fresh)) == 0)
	})
	t.Run("pipe form", func(t *testing.T) {
		s := set.From[int]([]int{5, 4})
		test.AssertEqual(t, set.ToSortedList(s), []int{4, 5})
	})
}

func TestAll(t *testing.T) {
	s := set.From[string]([]string{"a", "b", "c"})
	t.Run("for-in yields every member exactly once", func(t *testing.T) {
		seen := []string{}
		for e := range set.All(s) {
			seen = append(seen, e)
		}
		test.AssertEqual(t, len(seen), 3)
		test.AssertTrue(t, set.ContainsAll(s, seen))
		test.AssertEqual(t, set.Len(set.From[string](seen)), 3)
	})
	t.Run("composes with iterator pipelines", func(t *testing.T) {
		upper := iterator.Collect(iterator.Map(set.All(s), func(e string) string { return kukistring.ToUpper(e) }))
		test.AssertEqual(t, len(upper), 3)
		test.AssertTrue(t, slice.Contains(upper, "A"))
		test.AssertTrue(t, slice.Contains(upper, "C"))
	})
	t.Run("early exit stops the iterator", func(t *testing.T) {
		count := 0
		for e := range set.All(s) {
			test.AssertTrue(t, set.Contains(s, e))
			count = count + 1
			if count == 1 {
				break
			}
		}
		test.AssertEqual(t, count, 1)
	})
}

func TestUnion(t *testing.T) {
	a := set.From[string]([]string{"a", "b"})
	b := set.From[string]([]string{"b", "c"})
	u := set.Union(a, b)
	t.Run("correct size", func(t *testing.T) {
		test.AssertEqual(t, set.Len(u), 3)
	})
	t.Run("contains all elements", func(t *testing.T) {
		test.AssertTrue(t, set.Contains(u, "a"))
		test.AssertTrue(t, set.Contains(u, "b"))
		test.AssertTrue(t, set.Contains(u, "c"))
	})
}

func TestIntersection(t *testing.T) {
	a := set.From[string]([]string{"a", "b", "c"})
	b := set.From[string]([]string{"b", "c", "d"})
	i := set.Intersection(a, b)
	t.Run("correct size", func(t *testing.T) {
		test.AssertEqual(t, set.Len(i), 2)
	})
	t.Run("contains shared elements", func(t *testing.T) {
		test.AssertTrue(t, set.Contains(i, "b"))
		test.AssertTrue(t, set.Contains(i, "c"))
		test.AssertFalse(t, set.Contains(i, "a"))
		test.AssertFalse(t, set.Contains(i, "d"))
	})
	t.Run("disjoint sets yield empty", func(t *testing.T) {
		x := set.From[string]([]string{"x"})
		y := set.From[string]([]string{"y"})
		test.AssertTrue(t, set.IsEmpty(set.Intersection(x, y)))
	})
}

func TestDifference(t *testing.T) {
	a := set.From[string]([]string{"a", "b", "c"})
	b := set.From[string]([]string{"b", "c", "d"})
	d := set.Difference(a, b)
	t.Run("correct size", func(t *testing.T) {
		test.AssertEqual(t, set.Len(d), 1)
	})
	t.Run("only a-exclusive elements", func(t *testing.T) {
		test.AssertTrue(t, set.Contains(d, "a"))
		test.AssertFalse(t, set.Contains(d, "b"))
		test.AssertFalse(t, set.Contains(d, "d"))
	})
}

func TestSymmetricDifference(t *testing.T) {
	a := set.From[string]([]string{"a", "b", "c"})
	b := set.From[string]([]string{"b", "c", "d"})
	d := set.SymmetricDifference(a, b)
	t.Run("members of exactly one side", func(t *testing.T) {
		test.AssertEqual(t, set.Len(d), 2)
		test.AssertTrue(t, set.Contains(d, "a"))
		test.AssertTrue(t, set.Contains(d, "d"))
		test.AssertFalse(t, set.Contains(d, "b"))
		test.AssertFalse(t, set.Contains(d, "c"))
	})
	t.Run("with empty yields the other side", func(t *testing.T) {
		fresh := set.New[string]()
		test.AssertTrue(t, set.Equal(set.SymmetricDifference(a, fresh), a))
	})
	t.Run("a set against itself is empty", func(t *testing.T) {
		test.AssertTrue(t, set.IsEmpty(set.SymmetricDifference(a, a)))
	})
	t.Run("returns a new set", func(t *testing.T) {
		set.Add(d, "z")
		test.AssertFalse(t, set.Contains(a, "z"))
		test.AssertFalse(t, set.Contains(b, "z"))
	})
}

func TestClone(t *testing.T) {
	t.Run("same members", func(t *testing.T) {
		a := set.From[string]([]string{"a", "b"})
		test.AssertTrue(t, set.Equal(a, set.Clone(a)))
	})
	t.Run("mutating the clone leaves the original untouched", func(t *testing.T) {
		a := set.From[string]([]string{"a", "b"})
		c := set.Clone(a)
		set.Add(c, "z")
		set.Remove(a, "a")
		test.AssertFalse(t, set.Contains(a, "z"))
		test.AssertTrue(t, set.Contains(c, "a"))
		test.AssertEqual(t, set.Len(a), 1)
		test.AssertEqual(t, set.Len(c), 3)
	})
	t.Run("empty clones to empty", func(t *testing.T) {
		fresh := set.New[int]()
		c := set.Clone(fresh)
		test.AssertTrue(t, set.IsEmpty(c))
	})
}

type SubsetCase struct {
	name  string
	sub   []string
	super []string
	want  bool
}

func TestSubset(t *testing.T) {
	cases := []SubsetCase{SubsetCase{name: "proper subset", sub: []string{"a"}, super: []string{"a", "b"}, want: true}, SubsetCase{name: "equal sets", sub: []string{"a", "b"}, super: []string{"a", "b"}, want: true}, SubsetCase{name: "not a subset", sub: []string{"a", "c"}, super: []string{"a", "b"}, want: false}, SubsetCase{name: "empty is subset of all", sub: []string{}, super: []string{"a"}, want: true}}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			sub := set.From[string](tc.sub)
			super := set.From[string](tc.super)
			test.AssertEqual(t, set.Subset(sub, super), tc.want)
		})
	}
}

func TestSuperset(t *testing.T) {
	t.Run("superset", func(t *testing.T) {
		super := set.From[string]([]string{"a", "b", "c"})
		sub := set.From[string]([]string{"a", "b"})
		test.AssertTrue(t, set.Superset(super, sub))
	})
	t.Run("not superset", func(t *testing.T) {
		super := set.From[string]([]string{"a"})
		sub := set.From[string]([]string{"a", "b"})
		test.AssertFalse(t, set.Superset(super, sub))
	})
}

type EqualCase struct {
	name string
	a    []string
	b    []string
	want bool
}

func TestEqual(t *testing.T) {
	cases := []EqualCase{EqualCase{name: "equal", a: []string{"a", "b"}, b: []string{"b", "a"}, want: true}, EqualCase{name: "different elements", a: []string{"a"}, b: []string{"b"}, want: false}, EqualCase{name: "different sizes", a: []string{"a", "b"}, b: []string{"a"}, want: false}, EqualCase{name: "both empty", a: []string{}, b: []string{}, want: true}}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			a := set.From[string](tc.a)
			b := set.From[string](tc.b)
			test.AssertEqual(t, set.Equal(a, b), tc.want)
		})
	}
}

func TestIntersects(t *testing.T) {
	a := set.From[string]([]string{"a", "b"})
	b := set.From[string]([]string{"b", "c"})
	disjoint := set.From[string]([]string{"x", "y"})
	t.Run("shared member", func(t *testing.T) {
		test.AssertTrue(t, set.Intersects(a, b))
		test.AssertTrue(t, set.Intersects(b, a))
	})
	t.Run("disjoint sets", func(t *testing.T) {
		test.AssertFalse(t, set.Intersects(a, disjoint))
		test.AssertFalse(t, set.Intersects(disjoint, a))
	})
	t.Run("empty never intersects", func(t *testing.T) {
		fresh := set.New[string]()
		test.AssertFalse(t, set.Intersects(a, fresh))
		test.AssertFalse(t, set.Intersects(fresh, a))
		test.AssertFalse(t, set.Intersects(fresh, fresh))
	})
	t.Run("self-intersects when non-empty", func(t *testing.T) {
		test.AssertTrue(t, set.Intersects(a, a))
	})
}

func TestIntegerSet(t *testing.T) {
	s := set.From[int]([]int{1, 2, 3, 2})
	test.AssertEqual(t, set.Len(s), 3)
	test.AssertTrue(t, set.Contains(s, 2))
	set.Remove(s, 2)
	test.AssertEqual(t, set.Len(s), 2)
	test.AssertFalse(t, set.Contains(s, 2))
	other := set.From[int]([]int{3, 4})
	u := set.Union(s, other)
	test.AssertEqual(t, set.Len(u), 3)
	test.AssertTrue(t, set.Contains(u, 4))
}

func TestAliasMutationShared(t *testing.T) {
	a := set.From[string]([]string{"x"})
	b := a
	set.Add(b, "y")
	test.AssertEqual(t, set.Len(a), 2)
	test.AssertTrue(t, set.Contains(a, "y"))
}

func TestSetOpsReturnNewSets(t *testing.T) {
	a := set.From[string]([]string{"a", "b"})
	b := set.From[string]([]string{"b", "c"})
	u := set.Union(a, b)
	set.Add(u, "z")
	test.AssertFalse(t, set.Contains(a, "z"))
	test.AssertFalse(t, set.Contains(b, "z"))
	test.AssertEqual(t, set.Len(a), 2)
	test.AssertEqual(t, set.Len(b), 2)
}

func TestPipeForm(t *testing.T) {
	s := set.From[string]([]string{"a", "b"})
	test.AssertTrue(t, set.Contains(s, "a"))
	test.AssertFalse(t, set.Contains(s, "z"))
	items := set.ToSlice(s)
	test.AssertEqual(t, len(items), 2)
}
