// Generated by Kukicha (requires Go 1.27+)

package anthropic

import (
	"bufio"
	"context"
	"encoding/json/jsontext"
	"errors"
	"fmt"
	"kukicha.org/kukicha/stdlib/content"
	ctxpkg "kukicha.org/kukicha/stdlib/ctx"
	"kukicha.org/kukicha/stdlib/fetch"
	"kukicha.org/kukicha/stdlib/json"
	"kukicha.org/kukicha/stdlib/llm"
	kukistring "kukicha.org/kukicha/stdlib/string"
)

type rawContentBlock struct {
	Type      string         `json:"type"`
	Text      string         `json:"text,omitempty"`
	Thinking  string         `json:"thinking,omitempty"`
	ID        string         `json:"id,omitempty"`
	Name      string         `json:"name,omitempty"`
	Input     jsontext.Value `json:"input,omitempty"`
	ToolUseID string         `json:"tool_use_id,omitempty"`
	Content   jsontext.Value `json:"content,omitempty"`
	Source    jsontext.Value `json:"source,omitempty"`
}

type ThinkingConfig struct {
	Type         string `json:"type"`
	BudgetTokens int    `json:"budget_tokens,omitempty"`
}

type OutputConfig struct {
	Format any `json:"format,omitempty"`
}

type MessageRole string

const (
	MessageRoleUser      MessageRole = "user"
	MessageRoleAssistant MessageRole = "assistant"
)

func AllMessageRole() []MessageRole {
	return []MessageRole{MessageRoleUser, MessageRoleAssistant}
}

func ParseMessageRole(s string) (MessageRole, error) {
	switch s {
	case "user":
		return MessageRoleUser, nil
	case "assistant":
		return MessageRoleAssistant, nil
	}
	switch s {
	case "User":
		return MessageRoleUser, nil
	case "Assistant":
		return MessageRoleAssistant, nil
	}
	var zero MessageRole
	return zero, fmt.Errorf("invalid MessageRole %q (valid: \"user\", \"assistant\")", s)
}

func (e MessageRole) String() string {
	switch e {
	case MessageRoleUser:
		return "User"
	case MessageRoleAssistant:
		return "Assistant"
	default:
		return string(e)
	}
}

type Message struct {
	Role    MessageRole `json:"role"`
	Content any         `json:"content"`
}

type Tool struct {
	Name        string `json:"name"`
	Description string `json:"description,omitempty"`
	InputSchema any    `json:"input_schema"`
}

type ToolChoice struct {
	Type string `json:"type"`
	Name string `json:"name,omitempty"`
}

type Usage struct {
	InputTokens              int `json:"input_tokens"`
	OutputTokens             int `json:"output_tokens"`
	CacheCreationInputTokens int `json:"cache_creation_input_tokens,omitempty"`
	CacheReadInputTokens     int `json:"cache_read_input_tokens,omitempty"`
}

type rawResponse struct {
	ID           string            `json:"id"`
	Type         string            `json:"type"`
	Role         string            `json:"role"`
	Content      []rawContentBlock `json:"content"`
	Model        string            `json:"model"`
	StopReason   string            `json:"stop_reason"`
	StopSequence string            `json:"stop_sequence,omitempty"`
	Usage        Usage             `json:"usage"`
}

type Response struct {
	ID           string
	Type         string
	Role         string
	Content      []content.Content
	Model        string
	StopReason   string
	StopSequence string
	Usage        Usage
}

type MessagesRequest struct {
	Model         string    `json:"model"`
	Messages      []Message `json:"messages"`
	MaxTokens     int       `json:"max_tokens"`
	System        string    `json:"system,omitzero"`
	Temperature   float64   `json:"temperature,omitzero"`
	TopP          float64   `json:"top_p,omitzero"`
	TopK          int       `json:"top_k,omitzero"`
	StopSequences []string  `json:"stop_sequences,omitzero"`
	Stream        bool      `json:"stream,omitzero"`
	Tools         []Tool    `json:"tools,omitzero"`
	ToolChoice    any       `json:"tool_choice,omitzero"`
	Metadata      any       `json:"metadata,omitzero"`
	Thinking      any       `json:"thinking,omitzero"`
	Effort        string    `json:"effort,omitzero"`
	OutputConfig  any       `json:"output_config,omitzero"`
	InferenceGeo  string    `json:"inference_geo,omitzero"`
}

type rawStreamEvent struct {
	Type         string          `json:"type"`
	Index        int             `json:"index,omitempty"`
	Message      rawResponse     `json:"message,omitzero"`
	ContentBlock rawContentBlock `json:"content_block,omitzero"`
	Delta        rawDelta        `json:"delta,omitzero"`
	Usage        Usage           `json:"usage,omitzero"`
}

type rawDelta struct {
	Type         string `json:"type,omitempty"`
	Text         string `json:"text,omitempty"`
	Thinking     string `json:"thinking,omitempty"`
	PartialJSON  string `json:"partial_json,omitempty"`
	StopReason   string `json:"stop_reason,omitempty"`
	StopSequence string `json:"stop_sequence,omitempty"`
}

type Client struct {
	model            string
	baseURL          string
	path             string
	apiKey           string
	apiVersion       string
	system           string
	messages         []Message
	maxTokens        int
	temperature      float64
	topP             float64
	topK             int
	stopSequences    []string
	tools            []Tool
	toolChoice       any
	toolHandlers     map[string]func(string) (string, error)
	metadata         any
	thinking         any
	effort           string
	outputConfig     any
	inferenceGeo     string
	streamHandler    func(string)
	eventHandler     func(llm.StreamEvent)
	retryMaxAttempts int
	retryDelayMs     int
	ctx              context.Context
}

func anyToJsontext(v any) jsontext.Value {
	if v == nil {
		return nil
	}
	data, err := json.Bytes(v)
	if err != nil {
		return nil
	}
	return jsontext.Value(data)
}

func jsontextToAny(v jsontext.Value) any {
	if !v.IsValid() {
		return nil
	}
	var out any
	err_1 := json.ParseBytesInto(v, &out)
	if err_1 != nil {
		return nil
	}
	return out
}

func decodeToolResultContent(raw jsontext.Value) []content.Content {
	if !raw.IsValid() {
		return []content.Content{}
	}
	var v any
	err_2 := json.ParseBytesInto(raw, &v)
	if err_2 != nil {
		return []content.Content{}
	}
	if s, _isOk := v.(string); _isOk {
		return []content.Content{content.Text{Body: s}}
	}
	if items, _isOk := v.([]any); _isOk {
		out := []content.Content{}
		for _, it := range items {
			data, err_3 := json.Bytes(it)
			if err_3 != nil {
				data = nil
			}
			block := rawContentBlock{}
			err := json.ParseBytesInto(data, &block)
			if err == nil {
				out = append(out, decodeContentBlock(block))
			}
		}
		return out
	}
	return []content.Content{}
}

func encodeToolResultContent(items []content.Content) any {
	if len(items) == 1 {
		if t, ok := items[0].(content.Text); ok {
			return t.Body
		}
	}
	return encodeContent(items)
}

func decodeContentBlock(b rawContentBlock) content.Content {
	if b.Type == "text" {
		return content.Text{Body: b.Text}
	}
	if b.Type == "thinking" {
		return content.Thinking{Body: b.Thinking}
	}
	if b.Type == "tool_use" {
		inputMap := map[string]any{}
		decoded := jsontextToAny(b.Input)
		if m, _isOk := decoded.(map[string]any); _isOk {
			inputMap = m
		}
		return content.ToolUse{ID: b.ID, Name: b.Name, Input: content.ArgsMap{Value: inputMap}}
	}
	if b.Type == "tool_result" {
		return content.ToolResult{ToolUseID: b.ToolUseID, Items: decodeToolResultContent(b.Content)}
	}
	if b.Type == "image" {
		srcVal := jsontextToAny(b.Source)
		if m, _isOk := srcVal.(map[string]any); _isOk {
			typAny, hasTyp := m["type"]
			if hasTyp {
				if typStr, _isOk := typAny.(string); _isOk {
					if typStr == "base64" {
						mtAny, hasMt := m["media_type"]
						dataAny, hasData := m["data"]
						if hasMt && hasData {
							if mtStr, _isOk := mtAny.(string); _isOk {
								if dataStr, _isOk := dataAny.(string); _isOk {
									return content.Image{Payload: content.Encoded{Value: content.Base64{MediaType: mtStr, Data: dataStr}}}
								}
							}
						}
					}
				}
			}
		}
		return content.Image{Payload: content.Encoded{Value: content.RawSource{Value: srcVal}}}
	}
	return content.Raw{Type: b.Type, Data: b}
}

func encodeContentBlock(c content.Content) rawContentBlock {
	switch c := c.(type) {
	case content.Text:
		return rawContentBlock{Type: "text", Text: c.Body}
	case content.Thinking:
		return rawContentBlock{Type: "thinking", Thinking: c.Body}
	case content.ToolUse:
		inputVal := *new(any)
		if j, _isOk := c.Input.(content.ArgsJSON); _isOk {
			inputVal = j.Value
		}
		if m, _isOk := c.Input.(content.ArgsMap); _isOk {
			inputVal = m.Value
		}
		return rawContentBlock{Type: "tool_use", ID: c.ID, Name: c.Name, Input: anyToJsontext(inputVal)}
	case content.ToolResult:
		return rawContentBlock{Type: "tool_result", ToolUseID: c.ToolUseID, Content: anyToJsontext(encodeToolResultContent(c.Items))}
	case content.Image:
		sourceVal := *new(any)
		switch payload := c.Payload.(type) {
		case content.Inline:
			sourceVal = map[string]string{"type": "base64", "media_type": payload.MIMEType, "data": string(payload.Data)}
		case content.Encoded:
			switch src := payload.Value.(type) {
			case content.Base64:
				sourceVal = map[string]string{"type": "base64", "media_type": src.MediaType, "data": src.Data}
			case content.RawSource:
				sourceVal = src.Value
			default:
				panic("unreachable")
			}
		}
		return rawContentBlock{Type: "image", Source: anyToJsontext(sourceVal)}
	case content.Raw:
		rawStr := ""
		if s, _isOk := c.Data.(string); _isOk {
			rawStr = s
		} else {
			rawBytes, err_4 := json.Bytes(c.Data)
			if err_4 != nil {
				rawBytes = nil
			}
			rawStr = string(rawBytes)
		}
		return rawContentBlock{Type: c.Type, Text: rawStr}
	}
	return rawContentBlock{}
}

func decodeResponse(r rawResponse) Response {
	blocks := []content.Content{}
	for _, b := range r.Content {
		blocks = append(blocks, decodeContentBlock(b))
	}
	return Response{ID: r.ID, Type: r.Type, Role: r.Role, Content: blocks, Model: r.Model, StopReason: r.StopReason, StopSequence: r.StopSequence, Usage: r.Usage}
}

func encodeContent(blocks []content.Content) []rawContentBlock {
	out := []rawContentBlock{}
	for _, c := range blocks {
		out = append(out, encodeContentBlock(c))
	}
	return out
}

func New(model string) Client {
	return Client{model: model, apiVersion: "2023-06-01", maxTokens: 1024}
}

func BaseURL(c Client, url string) Client {
	c.baseURL = url
	return c
}

func Path(c Client, path string) Client {
	c.path = path
	return c
}

func APIKey(c Client, key string) Client {
	c.apiKey = key
	return c
}

func APIVersion(c Client, version string) Client {
	c.apiVersion = version
	return c
}

func System(c Client, system string) Client {
	c.system = system
	return c
}

func User(c Client, content string) Client {
	c.messages = append(c.messages, Message{Role: MessageRoleUser, Content: content})
	return c
}

func Assistant(c Client, content string) Client {
	c.messages = append(c.messages, Message{Role: MessageRoleAssistant, Content: content})
	return c
}

func AddMessage(c Client, role MessageRole, content any) Client {
	c.messages = append(c.messages, Message{Role: role, Content: content})
	return c
}

func ToolResult(c Client, toolUseID string, result string) Client {
	block := rawContentBlock{Type: "tool_result", ToolUseID: toolUseID, Content: anyToJsontext(result)}
	c.messages = append(c.messages, Message{Role: MessageRoleUser, Content: []rawContentBlock{block}})
	return c
}

func MaxTokens(c Client, tokens int) Client {
	c.maxTokens = tokens
	return c
}

func Temperature(c Client, temp float64) Client {
	c.temperature = temp
	return c
}

func TopP(c Client, p float64) Client {
	c.topP = p
	return c
}

func TopK(c Client, k int) Client {
	c.topK = k
	return c
}

func StopSequences(c Client, sequences []string) Client {
	c.stopSequences = sequences
	return c
}

func AdaptiveThinking(c Client) Client {
	c.thinking = ThinkingConfig{Type: "adaptive"}
	return c
}

func Thinking(c Client, budgetTokens int) Client {
	c.thinking = ThinkingConfig{Type: "enabled", BudgetTokens: budgetTokens}
	return c
}

type ThinkingEffort string

const (
	ThinkingEffortLow    ThinkingEffort = "low"
	ThinkingEffortMedium ThinkingEffort = "medium"
	ThinkingEffortHigh   ThinkingEffort = "high"
	ThinkingEffortMax    ThinkingEffort = "max"
)

func AllThinkingEffort() []ThinkingEffort {
	return []ThinkingEffort{ThinkingEffortLow, ThinkingEffortMedium, ThinkingEffortHigh, ThinkingEffortMax}
}

func ParseThinkingEffort(s string) (ThinkingEffort, error) {
	switch s {
	case "low":
		return ThinkingEffortLow, nil
	case "medium":
		return ThinkingEffortMedium, nil
	case "high":
		return ThinkingEffortHigh, nil
	case "max":
		return ThinkingEffortMax, nil
	}
	switch s {
	case "Low":
		return ThinkingEffortLow, nil
	case "Medium":
		return ThinkingEffortMedium, nil
	case "High":
		return ThinkingEffortHigh, nil
	case "Max":
		return ThinkingEffortMax, nil
	}
	var zero ThinkingEffort
	return zero, fmt.Errorf("invalid ThinkingEffort %q (valid: \"low\", \"medium\", \"high\", \"max\")", s)
}

func (e ThinkingEffort) String() string {
	switch e {
	case ThinkingEffortLow:
		return "Low"
	case ThinkingEffortMedium:
		return "Medium"
	case ThinkingEffortHigh:
		return "High"
	case ThinkingEffortMax:
		return "Max"
	default:
		return string(e)
	}
}

func WithThinkingEffort(c Client, effort ThinkingEffort) Client {
	c.effort = string(effort)
	return c
}

func OutputFormat(c Client, format any) Client {
	c.outputConfig = OutputConfig{Format: format}
	return c
}

type InferenceRegion string

const (
	InferenceRegionGlobal InferenceRegion = "global"
	InferenceRegionUS     InferenceRegion = "us"
)

func AllInferenceRegion() []InferenceRegion {
	return []InferenceRegion{InferenceRegionGlobal, InferenceRegionUS}
}

func ParseInferenceRegion(s string) (InferenceRegion, error) {
	switch s {
	case "global":
		return InferenceRegionGlobal, nil
	case "us":
		return InferenceRegionUS, nil
	}
	switch s {
	case "Global":
		return InferenceRegionGlobal, nil
	case "US":
		return InferenceRegionUS, nil
	}
	var zero InferenceRegion
	return zero, fmt.Errorf("invalid InferenceRegion %q (valid: \"global\", \"us\")", s)
}

func (e InferenceRegion) String() string {
	switch e {
	case InferenceRegionGlobal:
		return "Global"
	case InferenceRegionUS:
		return "US"
	default:
		return string(e)
	}
}

func WithInferenceRegion(c Client, region InferenceRegion) Client {
	c.inferenceGeo = string(region)
	return c
}

func AddTool(c Client, name string, description string, inputSchema any) Client {
	c.tools = append(c.tools, Tool{Name: name, Description: description, InputSchema: inputSchema})
	return c
}

func WithTool[T any, R any](c Client, name string, description string, schema any, handler func(T) (R, error)) Client {
	c = AddTool(c, name, description, schema)
	if c.toolHandlers == nil {
		c.toolHandlers = make(map[string]func(string) (string, error))
	}
	c.toolHandlers[name] = func(argsJSON string) (string, error) {
		var args T
		if argsJSON != "" {
			parseErr := json.ParseInto(argsJSON, &args)
			if parseErr != nil {
				return "", parseErr
			}
		}
		result, handlerErr := handler(args)
		if handlerErr != nil {
			return "", handlerErr
		}
		encoded, encErr := json.Bytes(result)
		if encErr != nil {
			return "", encErr
		}
		return string(encoded), nil
	}
	return c
}

func ToolChoiceAuto(c Client) Client {
	c.toolChoice = ToolChoice{Type: "auto"}
	return c
}

func ToolChoiceAny(c Client) Client {
	c.toolChoice = ToolChoice{Type: "any"}
	return c
}

func ToolChoiceTool(c Client, name string) Client {
	c.toolChoice = ToolChoice{Type: "tool", Name: name}
	return c
}

func Stream(c Client, handler func(string)) Client {
	c.streamHandler = handler
	return c
}

func StreamEvents(c Client, handler func(llm.StreamEvent)) Client {
	c.eventHandler = handler
	return c
}

func Retry(c Client, maxAttempts int, delayMs int) Client {
	c.retryMaxAttempts = maxAttempts
	c.retryDelayMs = delayMs
	return c
}

func WithContext(c Client, h ctxpkg.Handle) Client {
	c.ctx = h.Ctx
	return c
}

func Ask(c Client, prompt string) (string, error) {
	c = User(c, prompt)
	return doExecute(c)
}

func Send(c Client) (string, error) {
	return doExecute(c)
}

func AskRaw(c Client, prompt string) (Response, error) {
	c = User(c, prompt)
	return doExecuteRaw(c)
}

func SendRaw(c Client) (Response, error) {
	return doExecuteRaw(c)
}

func Complete(model string, prompt string) (string, error) {
	return Ask(New(model), prompt)
}

func CompleteWithSystem(model string, system string, prompt string) (string, error) {
	c := New(model)
	c = System(c, system)
	return Ask(c, prompt)
}

func FromResponse(c Client, resp Response) Client {
	c.messages = append(c.messages, Message{Role: MessageRoleAssistant, Content: encodeContent(resp.Content)})
	return c
}

func ExecuteToolUses(c Client, resp Response, handlers map[string]func(string) string) (Client, error) {
	c = FromResponse(c, resp)
	resultBlocks := []rawContentBlock{}
	hasAny := false
	for _, block := range resp.Content {
		if tu, _isOk := block.(content.ToolUse); _isOk {
			hasAny = true
			handler, ok := handlers[tu.Name]
			if !ok {
				return c, fmt.Errorf("no handler registered for tool: %v", tu.Name)
			}
			argsJSON := ""
			if j, _isOk := tu.Input.(content.ArgsJSON); _isOk {
				argsJSON = j.Value
			}
			if m, _isOk := tu.Input.(content.ArgsMap); _isOk {
				inputBytes, err_5 := json.Bytes(m.Value)
				if err_5 != nil {
					err_5 = fmt.Errorf("encode tool input: %w", err_5)
					var _zero0 Client
					return _zero0, err_5
				}
				argsJSON = string(inputBytes)
			}
			result := handler(argsJSON)
			resultBlocks = append(resultBlocks, rawContentBlock{Type: "tool_result", ToolUseID: tu.ID, Content: anyToJsontext(result)})
		}
	}
	if !hasAny {
		return c, nil
	}
	c.messages = append(c.messages, Message{Role: MessageRoleUser, Content: resultBlocks})
	return c, nil
}

func RunToolUses(c Client, resp Response) (Client, error) {
	c = FromResponse(c, resp)
	resultBlocks := []rawContentBlock{}
	hasAny := false
	for _, block := range resp.Content {
		if tu, _isOk := block.(content.ToolUse); _isOk {
			hasAny = true
			handler, ok := c.toolHandlers[tu.Name]
			if !ok {
				return c, fmt.Errorf("no handler registered for tool: %v", tu.Name)
			}
			argsJSON := ""
			if j, _isOk := tu.Input.(content.ArgsJSON); _isOk {
				argsJSON = j.Value
			}
			if m, _isOk := tu.Input.(content.ArgsMap); _isOk {
				inputBytes, err_6 := json.Bytes(m.Value)
				if err_6 != nil {
					err_6 = fmt.Errorf("encode tool input: %w", err_6)
					var _zero0 Client
					return _zero0, err_6
				}
				argsJSON = string(inputBytes)
			}
			result, callErr := handler(argsJSON)
			if callErr != nil {
				return c, callErr
			}
			resultBlocks = append(resultBlocks, rawContentBlock{Type: "tool_result", ToolUseID: tu.ID, Content: anyToJsontext(result)})
		}
	}
	if !hasAny {
		return c, nil
	}
	c.messages = append(c.messages, Message{Role: MessageRoleUser, Content: resultBlocks})
	return c, nil
}

func GetText(resp Response) string {
	result := ""
	for _, block := range resp.Content {
		if t, _isOk := block.(content.Text); _isOk {
			result = result + t.Body
		}
	}
	return result
}

func GetThinking(resp Response) string {
	result := ""
	for _, block := range resp.Content {
		if th, _isOk := block.(content.Thinking); _isOk {
			result = result + th.Body
		}
	}
	return result
}

func GetToolUses(resp Response) []content.ToolUse {
	uses := []content.ToolUse{}
	for _, block := range resp.Content {
		if tu, _isOk := block.(content.ToolUse); _isOk {
			uses = append(uses, tu)
		}
	}
	return uses
}

func HasToolUses(resp Response) bool {
	return resp.StopReason == "tool_use"
}

func resolveAPIKey(c Client) string {
	return llm.ResolveAPIKey("anthropic", c.apiKey)
}

func resolveBaseURL(c Client) string {
	return llm.ResolveBaseURL("anthropic", c.baseURL)
}

func resolvePath(c Client) string {
	if c.path != "" {
		return c.path
	}
	return "/v1/messages"
}

func buildRequest(c Client) MessagesRequest {
	req := MessagesRequest{Model: c.model, Messages: c.messages, MaxTokens: c.maxTokens}
	if c.system != "" {
		req.System = c.system
	}
	if c.temperature != 0.0 {
		req.Temperature = c.temperature
	}
	if c.topP != 0.0 {
		req.TopP = c.topP
	}
	if c.topK != 0 {
		req.TopK = c.topK
	}
	if len(c.stopSequences) != 0 {
		req.StopSequences = c.stopSequences
	}
	if len(c.tools) != 0 {
		req.Tools = c.tools
	}
	if c.toolChoice != nil {
		req.ToolChoice = c.toolChoice
	}
	if c.metadata != nil {
		req.Metadata = c.metadata
	}
	if c.thinking != nil {
		req.Thinking = c.thinking
	}
	if c.effort != "" {
		req.Effort = c.effort
	}
	if c.outputConfig != nil {
		req.OutputConfig = c.outputConfig
	}
	if c.inferenceGeo != "" {
		req.InferenceGeo = c.inferenceGeo
	}
	if c.streamHandler != nil || c.eventHandler != nil {
		req.Stream = true
	}
	return req
}

func doExecute(c Client) (string, error) {
	resp, err_7 := doExecuteRaw(c)
	if err_7 != nil {
		return "", err_7
	}
	return GetText(resp), nil
}

func doExecuteRaw(c Client) (Response, error) {
	if c.streamHandler != nil || c.eventHandler != nil {
		return doExecuteStreamRaw(c)
	}
	url := fmt.Sprintf("%v%v", resolveBaseURL(c), resolvePath(c))
	apiKey := resolveAPIKey(c)
	body := buildRequest(c)
	req := fetch.Header(fetch.Header(fetch.Method(fetch.New(url), fetch.HTTPMethodPOST), "Content-Type", "application/json"), "anthropic-version", c.apiVersion)
	if c.ctx != nil {
		req = fetch.WithContext(req, ctxpkg.FromContext(c.ctx))
	}
	if apiKey != "" {
		req = fetch.Header(req, "x-api-key", apiKey)
	}
	req = fetch.Body(req, body)
	if c.retryMaxAttempts > 1 {
		req = fetch.Retry(req, c.retryMaxAttempts, c.retryDelayMs)
	}
	resp, err_8 := fetch.Do(req)
	if err_8 != nil {
		var _zero0 Response
		return _zero0, err_8
	}
	rawResp := resp.Raw()
	if rawResp == nil {
		return Response{}, errors.New("Anthropic API response body unavailable")
	}
	defer rawResp.Body.Close()
	if resp.StatusCode >= 400 {
		return Response{}, fmt.Errorf("Anthropic API request failed (%v)", resp.StatusCode)
	}
	raw := rawResponse{}
	err_9 := json.ReadInto(rawResp.Body, &raw)
	if err_9 != nil {
		var _zero0 Response
		return _zero0, err_9
	}
	return decodeResponse(raw), nil
}

func emitStreamEvent(c Client, raw rawStreamEvent) {
	if c.eventHandler == nil {
		return
	}
	if raw.Type == "content_block_start" {
		if raw.ContentBlock.Type == "tool_use" {
			c.eventHandler(llm.ToolCallStart{Index: raw.Index, ID: raw.ContentBlock.ID, Name: raw.ContentBlock.Name})
		}
		return
	}
	if raw.Type == "content_block_delta" {
		if raw.Delta.Type == "text_delta" {
			c.eventHandler(llm.Delta{Body: raw.Delta.Text})
			return
		}
		if raw.Delta.Type == "thinking_delta" {
			c.eventHandler(llm.ThinkingDelta{Body: raw.Delta.Thinking})
			return
		}
		if raw.Delta.Type == "input_json_delta" {
			c.eventHandler(llm.ToolCallArgs{Index: raw.Index, Body: raw.Delta.PartialJSON})
			return
		}
		return
	}
	if raw.Type == "message_stop" {
		c.eventHandler(llm.Completed{})
		return
	}
	if raw.Type == "error" {
		c.eventHandler(llm.Error{Message: "Anthropic streaming error"})
		return
	}
}

func doExecuteStreamRaw(c Client) (Response, error) {
	url := fmt.Sprintf("%v%v", resolveBaseURL(c), resolvePath(c))
	apiKey := resolveAPIKey(c)
	body := buildRequest(c)
	req := fetch.Header(fetch.Header(fetch.Header(fetch.Method(fetch.New(url), fetch.HTTPMethodPOST), "Content-Type", "application/json"), "Accept", "text/event-stream"), "anthropic-version", c.apiVersion)
	if c.ctx != nil {
		req = fetch.WithContext(req, ctxpkg.FromContext(c.ctx))
	}
	if apiKey != "" {
		req = fetch.Header(req, "x-api-key", apiKey)
	}
	req = fetch.Body(req, body)
	if c.retryMaxAttempts > 1 {
		req = fetch.Retry(req, c.retryMaxAttempts, c.retryDelayMs)
	}
	resp, err_10 := fetch.Do(req)
	if err_10 != nil {
		var _zero0 Response
		return _zero0, err_10
	}
	rawResp := resp.Raw()
	if rawResp == nil {
		return Response{}, errors.New("Anthropic API response body unavailable")
	}
	defer rawResp.Body.Close()
	if resp.StatusCode >= 400 {
		return Response{}, fmt.Errorf("Anthropic API request failed (%v)", resp.StatusCode)
	}
	contentBlocks := map[int]rawContentBlock{}
	inputAccum := map[int]string{}
	thinkingAccum := map[int]string{}
	maxIdx := -1
	id := ""
	model := ""
	stopReason := ""
	stopSequence := ""
	usage := Usage{}
	sawMessageStop := false
	scanner := bufio.NewScanner(rawResp.Body)
	scanner.Buffer([]byte{}, 1048576)
	for scanner.Scan() {
		line := scanner.Text()
		if line == "" || kukistring.HasPrefix(line, "event:") || kukistring.HasPrefix(line, ":") {
			continue
		}
		if kukistring.HasPrefix(line, "data: ") {
			data := kukistring.TrimPrefix(line, "data: ")
			if data == "[DONE]" {
				break
			}
			evt := rawStreamEvent{}
			err_11 := json.ParseBytesInto([]byte(data), &evt)
			if err_11 != nil {
				fmt.Printf("anthropic parse failed: data=%v err=%v\n", data, err_11)
				if c.eventHandler != nil {
					c.eventHandler(llm.Error{Message: fmt.Sprintf("malformed frame: %v", err_11)})
				}
				return Response{}, fmt.Errorf("malformed stream frame: %v", err_11)
			}
			emitStreamEvent(c, evt)
			if evt.Type == "message_start" {
				if evt.Message.ID != "" {
					id = evt.Message.ID
				}
				if evt.Message.Model != "" {
					model = evt.Message.Model
				}
				if evt.Message.Usage.InputTokens != 0 || evt.Message.Usage.OutputTokens != 0 {
					usage = evt.Message.Usage
				}
			}
			if evt.Type == "content_block_start" {
				idx := evt.Index
				contentBlocks[idx] = evt.ContentBlock
				if idx > maxIdx {
					maxIdx = idx
				}
			}
			if evt.Type == "content_block_delta" {
				idx := evt.Index
				block := contentBlocks[idx]
				if evt.Delta.Type == "text_delta" {
					block.Type = "text"
					block.Text = block.Text + evt.Delta.Text
					if c.streamHandler != nil {
						c.streamHandler(evt.Delta.Text)
					}
				}
				if evt.Delta.Type == "thinking_delta" {
					block.Type = "thinking"
					thinkingAccum[idx] = thinkingAccum[idx] + evt.Delta.Thinking
					block.Thinking = thinkingAccum[idx]
					if c.streamHandler != nil {
						c.streamHandler(evt.Delta.Thinking)
					}
				}
				if evt.Delta.Type == "input_json_delta" {
					block.Type = "tool_use"
					inputAccum[idx] = inputAccum[idx] + evt.Delta.PartialJSON
					block.Input = jsontext.Value([]byte(inputAccum[idx]))
				}
				contentBlocks[idx] = block
				if idx > maxIdx {
					maxIdx = idx
				}
			}
			if evt.Type == "message_delta" {
				if evt.Delta.StopReason != "" {
					stopReason = evt.Delta.StopReason
				}
				if evt.Delta.StopSequence != "" {
					stopSequence = evt.Delta.StopSequence
				}
				if evt.Usage.InputTokens != 0 || evt.Usage.OutputTokens != 0 {
					usage = evt.Usage
				}
			}
			if evt.Type == "message_stop" {
				sawMessageStop = true
			}
			if evt.Type == "error" {
				if c.eventHandler != nil {
					c.eventHandler(llm.Error{Message: "Anthropic streaming error"})
				}
				return Response{}, errors.New("Anthropic streaming error")
			}
		}
	}
	err := scanner.Err()
	if err != nil {
		if c.eventHandler != nil {
			c.eventHandler(llm.Error{Message: fmt.Sprintf("%v", err)})
		}
		return Response{}, fmt.Errorf("%v", err)
	}
	if !sawMessageStop {
		return Response{}, errors.New("stream truncated: missing message_stop")
	}
	blocks := []content.Content{}
	for i := range maxIdx + 1 {
		_, ok := contentBlocks[i]
		if ok {
			blocks = append(blocks, decodeContentBlock(contentBlocks[i]))
		}
	}
	return Response{ID: id, Model: model, StopReason: stopReason, StopSequence: stopSequence, Usage: usage, Content: blocks}, nil
}
