// Generated by Kukicha (requires Go 1.27+)

package random_test

import (
	"fmt"
	"kukicha.org/kukicha/stdlib/random"
	kukistring "kukicha.org/kukicha/stdlib/string"
	"kukicha.org/kukicha/stdlib/test"
	"math"
	"slices"
	"testing"
)

type LengthCase struct {
	name string
}

func TestRandomStringLength(t *testing.T) {
	cases := []LengthCase{LengthCase{name: "lengths"}}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			s := random.String(10)
			test.AssertEqual(t, len(s), 10)
			zero := random.String(0)
			test.AssertEqual(t, zero, "")
		})
	}
}

func TestRandomInt(t *testing.T) {
	for range 100 {
		v := random.Int(5, 10)
		if v < 5 || v >= 10 {
			t.Errorf("random.Int(5, 10) = %d, out of range", v)
		}
	}
	test.AssertEqual(t, random.Int(7, 7), 7)
	test.AssertEqual(t, random.Int(10, 5), 10)
}

func TestRandomFloat(t *testing.T) {
	for range 100 {
		v := random.Float(1.0, 2.0)
		if v < 1.0 || v >= 2.0 {
			t.Errorf("random.Float(1.0, 2.0) = %f, out of range", v)
		}
	}
	test.AssertEqual(t, random.Float(3.5, 3.5), 3.5)
	test.AssertEqual(t, random.Float(2.0, 1.0), 2.0)
}

func TestChoice(t *testing.T) {
	items := []string{"a", "b", "c"}
	for range 50 {
		pick := random.Choice(items)
		if !(slices.Contains(items, pick)) {
			t.Errorf("random.Choice returned %v, not in items", pick)
		}
	}
}

func TestChoicePanicsOnEmpty(t *testing.T) {
	defer func() {
		if r := recover(); r != nil {
			return
		}
	}()
	random.Choice([]string{})
	t.Errorf("expected panic on empty items")
}

func TestIntPanicsOnRangeOverflow(t *testing.T) {
	defer func() {
		if r := recover(); r != nil {
			return
		}
	}()
	random.Int(math.MinInt, math.MaxInt)
	t.Errorf("expected panic when max - min overflows int")
}

func TestGeneratorChoicePanicsOnEmpty(t *testing.T) {
	defer func() {
		if r := recover(); r != nil {
			return
		}
	}()
	g := random.NewGenerator(1)
	g.Choice([]string{})
	t.Errorf("expected panic on empty items")
}

func TestGeneratorIntPanicsOnRangeOverflow(t *testing.T) {
	defer func() {
		if r := recover(); r != nil {
			return
		}
	}()
	g := random.NewGenerator(1)
	g.Int(math.MinInt, math.MaxInt)
	t.Errorf("expected panic when max - min overflows int")
}

func TestShuffleIsPermutation(t *testing.T) {
	items := []int{1, 2, 3, 4, 5, 6, 7, 8}
	shuffled := random.Shuffle(items)
	test.AssertEqual(t, len(shuffled), len(items))
	for _, x := range items {
		test.AssertTrue(t, slices.Contains(shuffled, x))
	}
	test.AssertEqual(t, items[0], 1)
	test.AssertEqual(t, items[7], 8)
}

func TestGeneratorDeterministic(t *testing.T) {
	a := random.NewGenerator(42)
	b := random.NewGenerator(42)
	for range 20 {
		test.AssertEqual(t, a.Int(0, 1000), b.Int(0, 1000))
		test.AssertEqual(t, a.Float(0.0, 1.0), b.Float(0.0, 1.0))
	}
	a = random.NewGenerator(7)
	b = random.NewGenerator(7)
	test.AssertEqual(t, a.String(12), b.String(12))
	test.AssertEqual(t, a.Shuffle([]int{1, 2, 3}), b.Shuffle([]int{1, 2, 3}))
}

func TestGeneratorDifferentSeedsDiffer(t *testing.T) {
	a := random.NewGenerator(1)
	b := random.NewGenerator(2)
	same := true
	for range 9 {
		if a.Int(0, 1000000000) != b.Int(0, 1000000000) {
			same = false
		}
	}
	test.AssertFalse(t, same)
}

func TestGeneratorRangeContracts(t *testing.T) {
	g := random.NewGenerator(99)
	test.AssertEqual(t, g.Int(7, 7), 7)
	test.AssertEqual(t, g.Int(10, 5), 10)
	test.AssertEqual(t, g.Float(3.5, 3.5), 3.5)
	test.AssertEqual(t, g.String(0), "")
}

func TestStringHasNoNul(t *testing.T) {
	for _, n := range []int{0, 1, 2, 3, 10, 32, 64, 257} {
		s := random.String(n)
		test.AssertEqual(t, len(s), n, fmt.Sprintf("String(%v) length", n))
		test.AssertFalse(t, kukistring.Contains(s, "\x00"), fmt.Sprintf("String(%v) contains NUL", n))
	}
	g := random.NewGenerator(1)
	for _, n := range []int{0, 1, 2, 10, 32, 64} {
		s := g.String(n)
		test.AssertEqual(t, len(s), n, fmt.Sprintf("Generator.String(%v) length", n))
		test.AssertFalse(t, kukistring.Contains(s, "\x00"), fmt.Sprintf("Generator.String(%v) contains NUL", n))
	}
}

func TestShuffleUsesLastIndex(t *testing.T) {
	g := random.NewGenerator(1)
	sawSwap := false
	for range 200 {
		shuffled := g.Shuffle([]int{1, 2})
		if shuffled[0] == 2 && shuffled[1] == 1 {
			sawSwap = true
		}
	}
	test.AssertTrue(t, sawSwap, "200 shuffles of a 2-element list never swapped")
	lastMoved := false
	for range 200 {
		shuffled := g.Shuffle([]int{1, 2, 3, 4, 5})
		if shuffled[4] != 5 {
			lastMoved = true
		}
	}
	test.AssertTrue(t, lastMoved, "original last element never left the final position")
}

const charset62 = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"

func TestStringCharsetMembership(t *testing.T) {
	sample := random.String(5000)
	for i := range len(sample) {
		ch := sample[i : i+1]
		if !kukistring.Contains(charset62, ch) {
			t.Errorf("String produced out-of-charset character %v at %v", ch, i)
		}
	}
}

func TestStringDistributionIsRoughlyUniform(t *testing.T) {
	sample := random.String(12400)
	counts := map[string]int{}
	total := 0
	for i := range len(sample) {
		ch := sample[i : i+1]
		counts[ch] = counts[ch] + 1
		total = total + 1
	}
	chi := 0.0
	for i := range len(charset62) {
		c := charset62[i : i+1]
		obs := counts[c]
		if obs <= 0 {
			t.Fatalf("charset character %v never appeared in %v samples", c, total)
		}
		expected := float64(total) / 62.0
		diff := float64(obs) - expected
		chi = chi + diff*diff/expected
	}
	if chi > 244.0 {
		t.Errorf("charset distribution not uniform: chi-square %v over %v samples (61 df, ceiling 244)", chi, total)
	}
}

func TestChoiceSpread(t *testing.T) {
	items := []string{"a", "b", "c", "d", "e", "f"}
	seen := map[string]bool{}
	for range 3000 {
		seen[random.Choice(items)] = true
	}
	test.AssertEqual(t, len(seen), 6)
}

func TestSampleDistinctAndFromSource(t *testing.T) {
	items := []int{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}
	for range 20 {
		picked := random.Sample(items, 4)
		test.AssertEqual(t, len(picked), 4)
		seen := map[int]bool{}
		for _, p := range picked {
			if seen[p] {
				t.Errorf("Sample returned duplicate %v", p)
			}
			seen[p] = true
			if !(slices.Contains(items, p)) {
				t.Errorf("Sample returned %v, not in items", p)
			}
		}
	}
}

func TestSampleBoundaries(t *testing.T) {
	items := []string{"a", "b", "c"}
	t.Run("n clamps to length", func(t *testing.T) {
		picked := random.Sample(items, 10)
		test.AssertEqual(t, len(picked), 3)
		seen := map[string]bool{}
		for _, p := range picked {
			seen[p] = true
		}
		test.AssertEqual(t, len(seen), 3, "clamped sample should stay distinct")
	})
	t.Run("n zero and negative yield empty", func(t *testing.T) {
		test.AssertEqual(t, len(random.Sample(items, 0)), 0)
		test.AssertEqual(t, len(random.Sample(items, -5)), 0)
	})
	t.Run("empty input yields empty", func(t *testing.T) {
		none := []string{}
		test.AssertEqual(t, len(random.Sample(none, 3)), 0)
	})
	t.Run("input untouched", func(t *testing.T) {
		random.Sample(items, 2)
		test.AssertEqual(t, items, []string{"a", "b", "c"})
	})
}

func TestGeneratorSample(t *testing.T) {
	items := []int{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}
	t.Run("same seed same picks", func(t *testing.T) {
		a := random.NewGenerator(42)
		b := random.NewGenerator(42)
		test.AssertEqual(t, a.Sample(items, 4), b.Sample(items, 4))
	})
	t.Run("clamps n", func(t *testing.T) {
		g := random.NewGenerator(1)
		test.AssertEqual(t, len(g.Sample(items, 100)), 10)
		test.AssertEqual(t, len(g.Sample(items, -1)), 0)
	})
	t.Run("distinct elements", func(t *testing.T) {
		g := random.NewGenerator(7)
		picked := g.Sample(items, 10)
		seen := map[int]bool{}
		for _, p := range picked {
			seen[p] = true
		}
		test.AssertEqual(t, len(seen), 10)
	})
}

func TestStringWithCharsetAndLength(t *testing.T) {
	alphabet := "ABC234"
	sample := random.StringWith(2000, alphabet)
	test.AssertEqual(t, len(sample), 2000)
	seen := map[string]bool{}
	for i := range len(sample) {
		ch := sample[i : i+1]
		if !kukistring.Contains(alphabet, ch) {
			t.Errorf("StringWith produced out-of-alphabet character %v at %v", ch, i)
		}
		seen[ch] = true
	}
	test.AssertEqual(t, len(seen), 6, "every alphabet character should appear")
	test.AssertEqual(t, random.StringWith(0, alphabet), "")
}

func TestStringWithPanicsOnEmptyAlphabet(t *testing.T) {
	test.AssertPanicsMessage(t, "empty alphabet", "empty alphabet", func() {
		random.StringWith(8, "")
	})
}
