// Generated by Kukicha (requires Go 1.26+)

package llm

import (
	"github.com/kukichalang/kukicha/stdlib/content"
	"maps"
)

//line stdlib/llm/llm.kuki:25
type JSONObject = map[string]any

//line stdlib/llm/llm.kuki:32
type SchemaProperty struct {
	Name        string
	Type        string
	Description string
}

//line stdlib/llm/llm.kuki:38
func Prop(name string, typ string, description string) SchemaProperty {
//line stdlib/llm/llm.kuki:39
	return SchemaProperty{Name: name, Type: typ, Description: description}
}

//line stdlib/llm/llm.kuki:43
func Schema(props []SchemaProperty) JSONObject {
//line stdlib/llm/llm.kuki:44
	properties := make(JSONObject)
//line stdlib/llm/llm.kuki:45
	for _, prop := range props {
//line stdlib/llm/llm.kuki:46
		properties[prop.Name] = map[string]any{"type": prop.Type, "description": prop.Description}
	}
//line stdlib/llm/llm.kuki:50
	return map[string]any{"type": "object", "properties": properties}
}

//line stdlib/llm/llm.kuki:58
func Required(schema JSONObject, names []string) JSONObject {
//line stdlib/llm/llm.kuki:59
	out := make(JSONObject)
//line stdlib/llm/llm.kuki:60
	maps.Copy(out, schema)
//line stdlib/llm/llm.kuki:61
	out["required"] = names
//line stdlib/llm/llm.kuki:62
	return out
}

//line stdlib/llm/llm.kuki:73
type StreamEvent interface{ isStreamEvent() }

type Delta struct {
	Body string
}

func (Delta) isStreamEvent() {}

type ThinkingDelta struct {
	Body string
}

func (ThinkingDelta) isStreamEvent() {}

type ToolCallStart struct {
	Index int
	ID    string
	Name  string
}

func (ToolCallStart) isStreamEvent() {}

type ToolCallArgs struct {
	Index int
	Body  string
}

func (ToolCallArgs) isStreamEvent() {}

type Completed struct{}

func (Completed) isStreamEvent() {}

type Error struct {
	Message string
}

func (Error) isStreamEvent() {}

//line stdlib/llm/llm.kuki:94
type Content = content.Content
