// Generated by Kukicha (requires Go 1.27+)

package datetime

import (
	"fmt"
	"time"
)

//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:19
type Time = time.Time

//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:24
type Duration = time.Duration

//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:30
type Layout string

const (
	LayoutISO8601     Layout = "iso8601"
	LayoutRFC3339     Layout = "rfc3339"
	LayoutRFC3339Nano Layout = "rfc3339nano"
	LayoutDate        Layout = "date"
	LayoutTime        Layout = "time"
	LayoutDateTime    Layout = "datetime"
	LayoutDateTimeT   Layout = "dateTimeT"
	LayoutKitchen     Layout = "kitchen"
	LayoutStamp       Layout = "stamp"
	LayoutRFC822      Layout = "rfc822"
	LayoutRFC1123     Layout = "rfc1123"
	LayoutANSIC       Layout = "ansic"
	LayoutUnixDate    Layout = "unixdate"
)

func AllLayout() []Layout {
	return []Layout{LayoutISO8601, LayoutRFC3339, LayoutRFC3339Nano, LayoutDate, LayoutTime, LayoutDateTime, LayoutDateTimeT, LayoutKitchen, LayoutStamp, LayoutRFC822, LayoutRFC1123, LayoutANSIC, LayoutUnixDate}
}

func ParseLayout(s string) (Layout, error) {
	switch s {
	case "iso8601":
		return LayoutISO8601, nil
	case "rfc3339":
		return LayoutRFC3339, nil
	case "rfc3339nano":
		return LayoutRFC3339Nano, nil
	case "date":
		return LayoutDate, nil
	case "time":
		return LayoutTime, nil
	case "datetime":
		return LayoutDateTime, nil
	case "dateTimeT":
		return LayoutDateTimeT, nil
	case "kitchen":
		return LayoutKitchen, nil
	case "stamp":
		return LayoutStamp, nil
	case "rfc822":
		return LayoutRFC822, nil
	case "rfc1123":
		return LayoutRFC1123, nil
	case "ansic":
		return LayoutANSIC, nil
	case "unixdate":
		return LayoutUnixDate, nil
	}
	switch s {
	case "ISO8601":
		return LayoutISO8601, nil
	case "RFC3339":
		return LayoutRFC3339, nil
	case "RFC3339Nano":
		return LayoutRFC3339Nano, nil
	case "Date":
		return LayoutDate, nil
	case "Time":
		return LayoutTime, nil
	case "DateTime":
		return LayoutDateTime, nil
	case "DateTimeT":
		return LayoutDateTimeT, nil
	case "Kitchen":
		return LayoutKitchen, nil
	case "Stamp":
		return LayoutStamp, nil
	case "RFC822":
		return LayoutRFC822, nil
	case "RFC1123":
		return LayoutRFC1123, nil
	case "ANSIC":
		return LayoutANSIC, nil
	case "UnixDate":
		return LayoutUnixDate, nil
	}
	var zero Layout
	return zero, fmt.Errorf("invalid Layout %q (valid: \"iso8601\", \"rfc3339\", \"rfc3339nano\", \"date\", \"time\", \"datetime\", \"dateTimeT\", \"kitchen\", \"stamp\", \"rfc822\", \"rfc1123\", \"ansic\", \"unixdate\")", s)
}

func (e Layout) String() string {
	return string(e)
}

//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:47
func Format(t Time, format Layout) string {
//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:48
	return t.Format(goLayout(format))
}

//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:52
func FormatCustom(t Time, layout string) string {
//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:53
	return t.Format(layout)
}

//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:57
func Parse(value string, format Layout) (Time, error) {
//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:58
	return time.Parse(goLayout(format), value)
}

//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:62
func ParseCustom(value string, layout string) (Time, error) {
//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:63
	return time.Parse(layout, value)
}

//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:66
func ParseInLocation(value string, format Layout, location string) (Time, error) {
//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:67
	loc, err_1 := time.LoadLocation(location)
//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:67
	if err_1 != nil {
		var _zero0 Time
//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:67
		return _zero0, err_1
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:68
	return time.ParseInLocation(goLayout(format), value, loc)
}

//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:72
func Now() Time {
//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:73
	return time.Now()
}

//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:77
func Today() Time {
//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:78
	now := time.Now()
//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:79
	return time.Date(now.Year(), now.Month(), now.Day(), 0, 0, 0, 0, now.Location())
}

//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:82
func Tomorrow() Time {
//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:83
	return Today().AddDate(0, 0, 1)
}

//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:86
func Yesterday() Time {
//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:87
	return Today().AddDate(0, 0, -1)
}

//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:91
func AddDays(t Time, days int) Time {
//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:92
	return t.AddDate(0, 0, days)
}

//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:94
func AddWeeks(t Time, weeks int) Time {
//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:95
	return t.AddDate(0, 0, weeks*7)
}

//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:97
func AddMonths(t Time, months int) Time {
//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:98
	return t.AddDate(0, months, 0)
}

//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:100
func AddYears(t Time, years int) Time {
//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:101
	return t.AddDate(years, 0, 0)
}

//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:103
func SubDays(t Time, days int) Time {
//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:104
	return t.AddDate(0, 0, -days)
}

//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:106
func SubWeeks(t Time, weeks int) Time {
//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:107
	return t.AddDate(0, 0, -weeks*7)
}

//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:109
func SubMonths(t Time, months int) Time {
//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:110
	return t.AddDate(0, -months, 0)
}

//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:112
func SubYears(t Time, years int) Time {
//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:113
	return t.AddDate(-years, 0, 0)
}

//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:117
func IsBetween(t Time, start Time, end Time) bool {
//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:118
	return (t.Equal(start) || t.After(start)) && (t.Equal(end) || t.Before(end))
}

//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:120
func IsSameDay(t1 Time, t2 Time) bool {
//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:121
	return t1.Year() == t2.Year() && t1.Month() == t2.Month() && t1.Day() == t2.Day()
}

//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:123
func IsToday(t Time) bool {
//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:124
	return IsSameDay(t, Now())
}

//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:126
func IsYesterday(t Time) bool {
//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:127
	return IsSameDay(t, Yesterday())
}

//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:129
func IsTomorrow(t Time) bool {
//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:130
	return IsSameDay(t, Tomorrow())
}

//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:132
func IsPast(t Time) bool {
//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:133
	return t.Before(time.Now())
}

//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:135
func IsFuture(t Time) bool {
//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:136
	return t.After(time.Now())
}

//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:140
func NowISO() string {
//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:141
	return time.Now().Format(time.RFC3339)
}

//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:143
func TimeAgo(t Time) string {
//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:144
	secs := int64(time.Since(t).Seconds())
//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:145
	if secs < 60 {
//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:146
		return "just now"
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:147
	mins := secs / 60
//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:148
	if mins < 60 {
//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:149
		return fmt.Sprintf("%vm ago", mins)
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:150
	hours := mins / 60
//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:151
	if hours < 24 {
//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:152
		return fmt.Sprintf("%vh ago", hours)
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:153
	days := hours / 24
//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:154
	if days < 30 {
//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:155
		return fmt.Sprintf("%vd ago", days)
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:156
	months := days / 30
//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:157
	if months < 12 {
//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:158
		return fmt.Sprintf("%vmo ago", months)
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:159
	years := days / 365
//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:160
	return fmt.Sprintf("%vy ago", years)
}

//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:163
func goLayout(format Layout) string {
//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:164
	switch format {
	case LayoutISO8601:
//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:166
		return "2006-01-02T15:04:05Z07:00"
	case LayoutRFC3339:
//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:168
		return time.RFC3339
	case LayoutRFC3339Nano:
//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:170
		return time.RFC3339Nano
	case LayoutDate:
//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:172
		return "2006-01-02"
	case LayoutTime:
//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:174
		return "15:04:05"
	case LayoutDateTime:
//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:176
		return "2006-01-02 15:04:05"
	case LayoutDateTimeT:
//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:178
		return "2006-01-02T15:04:05"
	case LayoutKitchen:
//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:180
		return time.Kitchen
	case LayoutStamp:
//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:182
		return time.Stamp
	case LayoutRFC822:
//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:184
		return time.RFC822
	case LayoutRFC1123:
//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:186
		return time.RFC1123
	case LayoutANSIC:
//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:188
		return time.ANSIC
	case LayoutUnixDate:
//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:190
		return time.UnixDate
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/datetime/datetime.kuki:191
	return time.RFC3339
}
