// Generated by Kukicha (requires Go 1.26+)

package log

import (
	"fmt"
	"github.com/kukichalang/kukicha/stdlib/color"
	"github.com/kukichalang/kukicha/stdlib/json"
	"github.com/kukichalang/kukicha/stdlib/term"
	"os"
	"strings"
	"time"
)

//line stdlib/log/log.kuki:29
type Level int

const (
	LevelDebug Level = 0
	LevelInfo  Level = 1
	LevelWarn  Level = 2
	LevelError Level = 3
	LevelFatal Level = 4
)

func AllLevel() []Level {
	return []Level{LevelDebug, LevelInfo, LevelWarn, LevelError, LevelFatal}
}

func (e Level) String() string {
	switch e {
	case LevelDebug:
		return "Debug"
	case LevelInfo:
		return "Info"
	case LevelWarn:
		return "Warn"
	case LevelError:
		return "Error"
	case LevelFatal:
		return "Fatal"
	default:
		return fmt.Sprintf("Level(%d)", int(e))
	}
}

//line stdlib/log/log.kuki:39
type Format string

const (
	FormatText Format = "text"
	FormatJSON Format = "json"
)

func AllFormat() []Format {
	return []Format{FormatText, FormatJSON}
}

func (e Format) String() string {
	return string(e)
}

func ParseFormat(s string) (Format, bool) {
	switch s {
	case "text":
		return FormatText, true
	case "json":
		return FormatJSON, true
	}
	var zero Format
	return zero, false
}

//line stdlib/log/log.kuki:45
type Logger struct {
	W      *os.File
	Level  Level
	Format Format
}

//line stdlib/log/log.kuki:51
func New(w *os.File) Logger {
//line stdlib/log/log.kuki:52
	return Logger{W: w, Level: LevelInfo, Format: FormatText}
}

//line stdlib/log/log.kuki:56
var defaultLogger Logger = New(os.Stderr)

//line stdlib/log/log.kuki:61
func SetLevel(level Level) {
//line stdlib/log/log.kuki:62
	defaultLogger.Level = level
}

//line stdlib/log/log.kuki:65
func SetFormat(format Format) {
//line stdlib/log/log.kuki:66
	defaultLogger.Format = format
}

//line stdlib/log/log.kuki:69
func levelName(level Level) string {
//line stdlib/log/log.kuki:70
	switch level {
	case LevelDebug:
//line stdlib/log/log.kuki:72
		return "DEBUG"
	case LevelInfo:
//line stdlib/log/log.kuki:74
		return "INFO"
	case LevelWarn:
//line stdlib/log/log.kuki:76
		return "WARN"
	case LevelError:
//line stdlib/log/log.kuki:78
		return "ERROR"
	case LevelFatal:
//line stdlib/log/log.kuki:80
		return "FATAL"
	default:
		panic("unreachable")
	}
}

//line stdlib/log/log.kuki:83
func colorize(level Level, name string, w *os.File) string {
//line stdlib/log/log.kuki:84
	if !term.ColorEnabledFor(w) {
//line stdlib/log/log.kuki:85
		return name
	}
//line stdlib/log/log.kuki:86
	s := color.NewStyler(w)
//line stdlib/log/log.kuki:87
	switch level {
	case LevelDebug:
//line stdlib/log/log.kuki:89
		return s.Gray(name)
	case LevelInfo:
//line stdlib/log/log.kuki:91
		return s.Cyan(name)
	case LevelWarn:
//line stdlib/log/log.kuki:93
		return s.Yellow(name)
	case LevelError:
//line stdlib/log/log.kuki:95
		return s.Red(name)
	case LevelFatal:
//line stdlib/log/log.kuki:97
		return s.Error(name)
	}
//line stdlib/log/log.kuki:98
	return name
}

//line stdlib/log/log.kuki:102
func needsQuoting(s string) bool {
//line stdlib/log/log.kuki:103
	if s == "" {
//line stdlib/log/log.kuki:104
		return true
	}
//line stdlib/log/log.kuki:105
	return strings.ContainsAny(s, " \t\n\"=")
}

//line stdlib/log/log.kuki:108
func formatValue(v any) string {
//line stdlib/log/log.kuki:109
	s := fmt.Sprintf("%v", v)
//line stdlib/log/log.kuki:110
	if !needsQuoting(s) {
//line stdlib/log/log.kuki:111
		return s
	}
//line stdlib/log/log.kuki:113
	return fmt.Sprintf("%q", s)
}

//line stdlib/log/log.kuki:117
func encodeJSONValue(v any) string {
//line stdlib/log/log.kuki:118
	bytes, err_1 := json.Bytes(v)
//line stdlib/log/log.kuki:118
	if err_1 != nil {
//line stdlib/log/log.kuki:118
		//line stdlib/log/log.kuki:119
		return fmt.Sprintf("%q", fmt.Sprintf("%v", v))
	}
//line stdlib/log/log.kuki:121
	return fmt.Sprintf("%s", bytes)
}

//line stdlib/log/log.kuki:125
func emitText(l Logger, level Level, msg string, kv []any) {
//line stdlib/log/log.kuki:126
	var b strings.Builder
//line stdlib/log/log.kuki:127
	b.WriteString(time.Now().Format("15:04:05"))
//line stdlib/log/log.kuki:128
	b.WriteString(" ")
//line stdlib/log/log.kuki:129
	b.WriteString(colorize(level, levelName(level), l.W))
//line stdlib/log/log.kuki:130
	b.WriteString(" ")
//line stdlib/log/log.kuki:131
	b.WriteString(msg)
//line stdlib/log/log.kuki:132
	i := 0
//line stdlib/log/log.kuki:133
	for i < len(kv) {
//line stdlib/log/log.kuki:134
		b.WriteString(" ")
//line stdlib/log/log.kuki:135
		key := fmt.Sprintf("%v", kv[i])
//line stdlib/log/log.kuki:136
		b.WriteString(key)
//line stdlib/log/log.kuki:137
		b.WriteString("=")
//line stdlib/log/log.kuki:138
		if i+1 < len(kv) {
//line stdlib/log/log.kuki:139
			b.WriteString(formatValue(kv[i+1]))
		} else {
//line stdlib/log/log.kuki:141
			b.WriteString("MISSING_VALUE")
		}
//line stdlib/log/log.kuki:142
		i = i + 2
	}
//line stdlib/log/log.kuki:143
	b.WriteString("\n")
//line stdlib/log/log.kuki:144
	fmt.Fprint(l.W, b.String())
}

//line stdlib/log/log.kuki:148
func emitJSON(l Logger, level Level, msg string, kv []any) {
//line stdlib/log/log.kuki:149
	var b strings.Builder
//line stdlib/log/log.kuki:150
	b.WriteString("{\"time\":")
//line stdlib/log/log.kuki:151
	b.WriteString(encodeJSONValue(time.Now().Format(time.RFC3339)))
//line stdlib/log/log.kuki:152
	b.WriteString(",\"level\":")
//line stdlib/log/log.kuki:153
	b.WriteString(encodeJSONValue(levelName(level)))
//line stdlib/log/log.kuki:154
	b.WriteString(",\"msg\":")
//line stdlib/log/log.kuki:155
	b.WriteString(encodeJSONValue(msg))
//line stdlib/log/log.kuki:156
	i := 0
//line stdlib/log/log.kuki:157
	for i < len(kv) {
//line stdlib/log/log.kuki:158
		b.WriteString(",")
//line stdlib/log/log.kuki:159
		key := fmt.Sprintf("%v", kv[i])
//line stdlib/log/log.kuki:160
		b.WriteString(encodeJSONValue(key))
//line stdlib/log/log.kuki:161
		b.WriteString(":")
//line stdlib/log/log.kuki:162
		if i+1 < len(kv) {
//line stdlib/log/log.kuki:163
			b.WriteString(encodeJSONValue(kv[i+1]))
		} else {
//line stdlib/log/log.kuki:165
			b.WriteString(encodeJSONValue("MISSING_VALUE"))
		}
//line stdlib/log/log.kuki:166
		i = i + 2
	}
//line stdlib/log/log.kuki:167
	b.WriteString("}\n")
//line stdlib/log/log.kuki:168
	fmt.Fprint(l.W, b.String())
}

//line stdlib/log/log.kuki:171
func (l Logger) emit(level Level, msg string, kv []any) {
//line stdlib/log/log.kuki:172
	if level < l.Level {
//line stdlib/log/log.kuki:173
		return
	}
//line stdlib/log/log.kuki:174
	switch l.Format {
	case FormatJSON:
//line stdlib/log/log.kuki:176
		emitJSON(l, level, msg, kv)
	case FormatText:
//line stdlib/log/log.kuki:178
		emitText(l, level, msg, kv)
	default:
		panic("unreachable")
	}
}

//line stdlib/log/log.kuki:182
func (l Logger) Debug(msg string, kv ...any) {
//line stdlib/log/log.kuki:183
	l.emit(LevelDebug, msg, kv)
}

//line stdlib/log/log.kuki:185
func (l Logger) Info(msg string, kv ...any) {
//line stdlib/log/log.kuki:186
	l.emit(LevelInfo, msg, kv)
}

//line stdlib/log/log.kuki:188
func (l Logger) Warn(msg string, kv ...any) {
//line stdlib/log/log.kuki:189
	l.emit(LevelWarn, msg, kv)
}

//line stdlib/log/log.kuki:191
func (l Logger) Error(msg string, kv ...any) {
//line stdlib/log/log.kuki:192
	l.emit(LevelError, msg, kv)
}

//line stdlib/log/log.kuki:195
func (l Logger) Fatal(msg string, kv ...any) {
//line stdlib/log/log.kuki:196
	l.emit(LevelFatal, msg, kv)
//line stdlib/log/log.kuki:197
	os.Exit(1)
}

//line stdlib/log/log.kuki:201
func Debug(msg string, kv ...any) {
//line stdlib/log/log.kuki:202
	defaultLogger.emit(LevelDebug, msg, kv)
}

//line stdlib/log/log.kuki:204
func Info(msg string, kv ...any) {
//line stdlib/log/log.kuki:205
	defaultLogger.emit(LevelInfo, msg, kv)
}

//line stdlib/log/log.kuki:207
func Warn(msg string, kv ...any) {
//line stdlib/log/log.kuki:208
	defaultLogger.emit(LevelWarn, msg, kv)
}

//line stdlib/log/log.kuki:210
func Error(msg string, kv ...any) {
//line stdlib/log/log.kuki:211
	defaultLogger.emit(LevelError, msg, kv)
}

//line stdlib/log/log.kuki:213
func Fatal(msg string, kv ...any) {
//line stdlib/log/log.kuki:214
	defaultLogger.emit(LevelFatal, msg, kv)
//line stdlib/log/log.kuki:215
	os.Exit(1)
}
