// Generated by Kukicha (requires Go 1.27+)

package log

import (
	"fmt"
	"kukicha.org/kukicha/stdlib/color"
	"kukicha.org/kukicha/stdlib/datetime"
	"kukicha.org/kukicha/stdlib/json"
	"kukicha.org/kukicha/stdlib/random"
	"kukicha.org/kukicha/stdlib/slice"
	kukistring "kukicha.org/kukicha/stdlib/string"
	"kukicha.org/kukicha/stdlib/term"
	"os"
	"strings"
)

type Level int

const (
	LevelDebug Level = 0
	LevelInfo  Level = 1
	LevelWarn  Level = 2
	LevelError Level = 3
	LevelFatal Level = 4
)

func AllLevel() []Level {
	return []Level{LevelDebug, LevelInfo, LevelWarn, LevelError, LevelFatal}
}

func (e Level) String() string {
	switch e {
	case LevelDebug:
		return "Debug"
	case LevelInfo:
		return "Info"
	case LevelWarn:
		return "Warn"
	case LevelError:
		return "Error"
	case LevelFatal:
		return "Fatal"
	default:
		return fmt.Sprintf("Level(%d)", int(e))
	}
}

type Format string

const (
	FormatText Format = "text"
	FormatJSON Format = "json"
)

func AllFormat() []Format {
	return []Format{FormatText, FormatJSON}
}

func ParseFormat(s string) (Format, error) {
	switch s {
	case "text":
		return FormatText, nil
	case "json":
		return FormatJSON, nil
	}
	switch s {
	case "Text":
		return FormatText, nil
	case "JSON":
		return FormatJSON, nil
	}
	var zero Format
	return zero, fmt.Errorf("invalid Format %q (valid: \"text\", \"json\")", s)
}

func (e Format) String() string {
	switch e {
	case FormatText:
		return "Text"
	case FormatJSON:
		return "JSON"
	default:
		return string(e)
	}
}

type Logger struct {
	W             *os.File
	Level         Level
	Format        Format
	Service       string
	Environment   string
	Component     string
	CorrelationID string
	Fields        []any
}

func New(w *os.File) Logger {
	return Logger{W: w, Level: LevelInfo, Format: FormatText}
}

func With(l Logger, kv ...any) Logger {
	return Logger{W: l.W, Level: l.Level, Format: l.Format, Service: l.Service, Environment: l.Environment, Component: l.Component, CorrelationID: l.CorrelationID, Fields: slice.Concat([][]any{l.Fields, kv})}
}

func NewCorrelationID() string {
	return random.String(16)
}

var defaultLogger Logger = New(os.Stderr)

func SetLevel(level Level) {
	defaultLogger.Level = level
}

func SetFormat(format Format) {
	defaultLogger.Format = format
}

func SetService(name string) {
	defaultLogger.Service = name
}

func SetEnvironment(name string) {
	defaultLogger.Environment = name
}

func SetComponent(name string) {
	defaultLogger.Component = name
}

func SetCorrelationID(id string) {
	defaultLogger.CorrelationID = id
}

func levelName(level Level) string {
	switch level {
	case LevelDebug:
		return "DEBUG"
	case LevelInfo:
		return "INFO"
	case LevelWarn:
		return "WARN"
	case LevelError:
		return "ERROR"
	case LevelFatal:
		return "FATAL"
	default:
		panic("unreachable")
	}
}

func colorize(level Level, name string, w *os.File) string {
	if !term.ColorEnabledFor(w) {
		return name
	}
	s := color.NewStyler(w)
	switch level {
	case LevelDebug:
		return s.Gray(name)
	case LevelInfo:
		return s.Cyan(name)
	case LevelWarn:
		return s.Yellow(name)
	case LevelError:
		return s.Red(name)
	case LevelFatal:
		return s.Error(name)
	}
	return name
}

func needsQuoting(s string) bool {
	if s == "" {
		return true
	}
	return kukistring.ContainsAny(s, " \t\n\"=")
}

func formatValue(v any) string {
	s := fmt.Sprintf("%v", v)
	if !needsQuoting(s) {
		return s
	}
	return fmt.Sprintf("%q", s)
}

func encodeJSONValue(v any) string {
	bytes, err_1 := json.Bytes(v)
	if err_1 != nil {
		return fmt.Sprintf("%q", fmt.Sprintf("%v", v))
	}
	return string(bytes)
}

func metaPairs(l Logger) []any {
	out := []any{}
	if l.Service != "" {
		out = append(out, "service", l.Service)
	}
	if l.Environment != "" {
		out = append(out, "environment", l.Environment)
	}
	if l.Component != "" {
		out = append(out, "component", l.Component)
	}
	if l.CorrelationID != "" {
		out = append(out, "correlation_id", l.CorrelationID)
	}
	return out
}

func withMeta(l Logger, kv []any) []any {
	out := metaPairs(l)
	for _, v := range l.Fields {
		out = append(out, v)
	}
	for _, v := range kv {
		out = append(out, v)
	}
	return out
}

func emitText(l Logger, level Level, msg string, kv []any) {
	kv = withMeta(l, kv)
	var b strings.Builder
	b.WriteString(datetime.Now().Format("15:04:05"))
	b.WriteString(" ")
	b.WriteString(colorize(level, levelName(level), l.W))
	b.WriteString(" ")
	b.WriteString(msg)
	i := 0
	for i < len(kv) {
		b.WriteString(" ")
		key := fmt.Sprintf("%v", kv[i])
		b.WriteString(key)
		b.WriteString("=")
		if i+1 < len(kv) {
			b.WriteString(formatValue(kv[i+1]))
		} else {
			b.WriteString("MISSING_VALUE")
		}
		i = i + 2
	}
	b.WriteString("\n")
	fmt.Fprint(l.W, b.String())
}

func emitJSON(l Logger, level Level, msg string, kv []any) {
	kv = withMeta(l, kv)
	var b strings.Builder
	b.WriteString("{\"time\":")
	b.WriteString(encodeJSONValue(datetime.NowISO()))
	b.WriteString(",\"level\":")
	b.WriteString(encodeJSONValue(levelName(level)))
	b.WriteString(",\"msg\":")
	b.WriteString(encodeJSONValue(msg))
	i := 0
	for i < len(kv) {
		b.WriteString(",")
		key := fmt.Sprintf("%v", kv[i])
		b.WriteString(encodeJSONValue(key))
		b.WriteString(":")
		if i+1 < len(kv) {
			b.WriteString(encodeJSONValue(kv[i+1]))
		} else {
			b.WriteString(encodeJSONValue("MISSING_VALUE"))
		}
		i = i + 2
	}
	b.WriteString("}\n")
	fmt.Fprint(l.W, b.String())
}

func (l Logger) emit(level Level, msg string, kv []any) {
	if level < l.Level {
		return
	}
	switch l.Format {
	case FormatJSON:
		emitJSON(l, level, msg, kv)
	case FormatText:
		emitText(l, level, msg, kv)
	default:
		panic("unreachable")
	}
}

func (l Logger) Debug(msg string, kv ...any) {
	l.emit(LevelDebug, msg, kv)
}

func (l Logger) Info(msg string, kv ...any) {
	l.emit(LevelInfo, msg, kv)
}

func (l Logger) Warn(msg string, kv ...any) {
	l.emit(LevelWarn, msg, kv)
}

func (l Logger) Error(msg string, kv ...any) {
	l.emit(LevelError, msg, kv)
}

func (l Logger) Fatal(msg any, kv ...any) {
	l.emit(LevelFatal, fmt.Sprint(msg), kv)
	os.Exit(1)
}

type Timer struct {
	Logger    Logger
	Operation string
	StartedAt datetime.Time
}

func (l Logger) StartTimer(operation string) Timer {
	return Timer{Logger: l, Operation: operation, StartedAt: datetime.Now()}
}

func (t *Timer) Stop(kv ...any) {
	all := []any{}
	for _, v := range kv {
		all = append(all, v)
	}
	all = append(all, "operation", t.Operation, "duration_ms", datetime.Now().Sub(t.StartedAt).Milliseconds())
	t.Logger.emit(LevelInfo, "operation complete", all)
}

func (t *Timer) Fail(reason string, kv ...any) {
	all := []any{}
	for _, v := range kv {
		all = append(all, v)
	}
	all = append(all, "operation", t.Operation, "duration_ms", datetime.Now().Sub(t.StartedAt).Milliseconds(), "reason", reason)
	t.Logger.emit(LevelError, "operation failed", all)
}

func Debug(msg string, kv ...any) {
	defaultLogger.emit(LevelDebug, msg, kv)
}

func Info(msg string, kv ...any) {
	defaultLogger.emit(LevelInfo, msg, kv)
}

func Warn(msg string, kv ...any) {
	defaultLogger.emit(LevelWarn, msg, kv)
}

func Error(msg string, kv ...any) {
	defaultLogger.emit(LevelError, msg, kv)
}

func Fatal(msg any, kv ...any) {
	defaultLogger.emit(LevelFatal, fmt.Sprint(msg), kv)
	os.Exit(1)
}
