// Generated by Kukicha (requires Go 1.27+)

package maps

import (
	"cmp"
	gomaps "maps"
	"slices"
)

func Keys[K comparable, V any](m map[K]V) []K {
	keys := make([]K, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	return keys
}

func Values[K comparable, V any](m map[K]V) []V {
	values := make([]V, 0, len(m))
	for _, v := range m {
		values = append(values, v)
	}
	return values
}

func Contains[K comparable, V any](m map[K]V, k K) bool {
	_, ok := m[k]
	return ok
}

func GetOr[K comparable, V any](m map[K]V, k K, defaultValue V) V {
	v, ok := m[k]
	if !ok {
		return defaultValue
	}
	return v
}

func Merge[K comparable, V any](base map[K]V, overlay map[K]V) map[K]V {
	result := make(map[K]V, len(base)+len(overlay))
	gomaps.Copy(result, base)
	gomaps.Copy(result, overlay)
	return result
}

func SortedKeys[K cmp.Ordered, V any](m map[K]V) []K {
	keys := make([]K, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	slices.Sort(keys)
	return keys
}

func Pick[K comparable, V any](m map[K]V, keys []K) map[K]V {
	result := map[K]V{}
	for _, k := range keys {
		v, ok := m[k]
		if ok {
			result[k] = v
		}
	}
	return result
}

func Clone[K comparable, V any](m map[K]V) map[K]V {
	result := make(map[K]V, len(m))
	gomaps.Copy(result, m)
	return result
}

func Omit[K comparable, V any](m map[K]V, keys []K) map[K]V {
	excluded := map[K]bool{}
	for _, k := range keys {
		excluded[k] = true
	}
	result := map[K]V{}
	for k, v := range m {
		if !excluded[k] {
			result[k] = v
		}
	}
	return result
}

func Filter[K comparable, V any](m map[K]V, keep func(K, V) bool) map[K]V {
	result := map[K]V{}
	for k, v := range m {
		if keep(k, v) {
			result[k] = v
		}
	}
	return result
}

func MapValues[K comparable, V any, R any](m map[K]V, transform func(V) R) map[K]R {
	result := map[K]R{}
	for k, v := range m {
		result[k] = transform(v)
	}
	return result
}

func Invert[K comparable, V comparable](m map[K]V) map[V]K {
	result := map[V]K{}
	for k, v := range m {
		result[v] = k
	}
	return result
}
