// Generated by Kukicha (requires Go 1.26+)

package url

import (
	"codeberg.org/kukichalang/kukicha/stdlib/slice"
	"codeberg.org/kukichalang/kukicha/stdlib/sort"
	kukistring "codeberg.org/kukichalang/kukicha/stdlib/string"
	"errors"
	"fmt"
	"maps"
	gourl "net/url"
	"path"
)

//line stdlib/url/url.kuki:32
type Parsed struct {
	Scheme   string
	Host     string
	Path     string
	Fragment string
	Params   map[string]string
	Raw      string
}

//line stdlib/url/url.kuki:43
type ParsedMulti struct {
	Scheme   string
	Host     string
	Path     string
	Fragment string
	Params   map[string][]string
	Raw      string
}

//line stdlib/url/url.kuki:53
func Parse(s string) (Parsed, error) {
//line stdlib/url/url.kuki:54
	u, err_1 := gourl.Parse(s)
//line stdlib/url/url.kuki:54
	if err_1 != nil {
		var _zero0 Parsed
//line stdlib/url/url.kuki:54
		return _zero0, err_1
	}
//line stdlib/url/url.kuki:56
	q := map[string][]string(u.Query())
//line stdlib/url/url.kuki:57
	flat := make(map[string]string)
//line stdlib/url/url.kuki:58
	for k, vs := range q {
//line stdlib/url/url.kuki:59
		if len(vs) > 0 {
//line stdlib/url/url.kuki:60
			flat[k] = vs[len(vs)-1]
		}
	}
//line stdlib/url/url.kuki:62
	return Parsed{Scheme: u.Scheme, Host: u.Host, Path: u.Path, Fragment: u.Fragment, Params: flat, Raw: s}, nil
}

//line stdlib/url/url.kuki:73
func ParseMulti(s string) (ParsedMulti, error) {
//line stdlib/url/url.kuki:74
	u, err_2 := gourl.Parse(s)
//line stdlib/url/url.kuki:74
	if err_2 != nil {
		var _zero0 ParsedMulti
//line stdlib/url/url.kuki:74
		return _zero0, err_2
	}
//line stdlib/url/url.kuki:76
	q := map[string][]string(u.Query())
//line stdlib/url/url.kuki:77
	multi := make(map[string][]string)
//line stdlib/url/url.kuki:78
	maps.Copy(multi, q)
//line stdlib/url/url.kuki:80
	return ParsedMulti{Scheme: u.Scheme, Host: u.Host, Path: u.Path, Fragment: u.Fragment, Params: multi, Raw: s}, nil
}

//line stdlib/url/url.kuki:91
type Builder struct {
	base   string
	keys   []string
	values []string
}

//line stdlib/url/url.kuki:99
func New(base string) Builder {
//line stdlib/url/url.kuki:100
	return Builder{base: base, keys: make([]string, 0), values: make([]string, 0)}
}

//line stdlib/url/url.kuki:110
func Param(b Builder, name string, value any) Builder {
//line stdlib/url/url.kuki:111
	b.keys = append(b.keys, name)
//line stdlib/url/url.kuki:112
	b.values = append(b.values, fmt.Sprint(value))
//line stdlib/url/url.kuki:113
	return b
}

//line stdlib/url/url.kuki:117
func String(b Builder) string {
//line stdlib/url/url.kuki:118
	if len(b.keys) == 0 {
//line stdlib/url/url.kuki:119
		return b.base
	}
//line stdlib/url/url.kuki:121
	parts := make([]string, 0, len(b.keys))
//line stdlib/url/url.kuki:122
	for i, k := range b.keys {
//line stdlib/url/url.kuki:123
		parts = append(parts, gourl.QueryEscape(k)+"="+gourl.QueryEscape(b.values[i]))
	}
//line stdlib/url/url.kuki:124
	query := kukistring.Join(parts, "&")
//line stdlib/url/url.kuki:126
	sep := "?"
//line stdlib/url/url.kuki:127
	if kukistring.Contains(b.base, "?") {
//line stdlib/url/url.kuki:128
		sep = "&"
	}
//line stdlib/url/url.kuki:129
	return b.base + sep + query
}

//line stdlib/url/url.kuki:133
func Escape(s string) string {
//line stdlib/url/url.kuki:134
	return gourl.QueryEscape(s)
}

//line stdlib/url/url.kuki:138
func Unescape(s string) (string, error) {
//line stdlib/url/url.kuki:139
	return gourl.QueryUnescape(s)
}

//line stdlib/url/url.kuki:150
func CleanPath(p string) (string, error) {
//line stdlib/url/url.kuki:151
	if p == "" {
//line stdlib/url/url.kuki:152
		return "", errors.New("path is empty")
	}
//line stdlib/url/url.kuki:153
	if kukistring.Contains(p, "\x00") {
//line stdlib/url/url.kuki:154
		return "", errors.New("path contains NUL byte")
	}
//line stdlib/url/url.kuki:155
	if kukistring.Contains(p, "\\") {
//line stdlib/url/url.kuki:156
		return "", errors.New("path contains backslash")
	}
//line stdlib/url/url.kuki:157
	lower := kukistring.ToLower(p)
//line stdlib/url/url.kuki:158
	if kukistring.Contains(lower, "%2e%2e") || kukistring.Contains(lower, "%2f") || kukistring.Contains(lower, "%5c") {
//line stdlib/url/url.kuki:159
		return "", errors.New("path contains percent-encoded traversal")
	}
//line stdlib/url/url.kuki:163
	if slice.Contains(kukistring.Split(p, "/"), "..") {
//line stdlib/url/url.kuki:164
		return "", errors.New("path contains '..' segment")
	}
//line stdlib/url/url.kuki:165
	cleaned := path.Clean(p)
//line stdlib/url/url.kuki:166
	if !kukistring.HasPrefix(cleaned, "/") {
//line stdlib/url/url.kuki:167
		cleaned = "/" + cleaned
	}
//line stdlib/url/url.kuki:168
	return cleaned, nil
}

//line stdlib/url/url.kuki:177
func IsSubpath(base string, candidate string) bool {
//line stdlib/url/url.kuki:178
	cleanBase, err_3 := CleanPath(base)
//line stdlib/url/url.kuki:178
	if err_3 != nil {
//line stdlib/url/url.kuki:178
		return false
	}
//line stdlib/url/url.kuki:179
	cleanCand, err_4 := CleanPath(candidate)
//line stdlib/url/url.kuki:179
	if err_4 != nil {
//line stdlib/url/url.kuki:179
		return false
	}
//line stdlib/url/url.kuki:180
	trimmedBase := kukistring.TrimRight(cleanBase, "/")
//line stdlib/url/url.kuki:181
	if trimmedBase == "" {
//line stdlib/url/url.kuki:182
		return true
	}
//line stdlib/url/url.kuki:183
	if cleanCand == trimmedBase {
//line stdlib/url/url.kuki:184
		return true
	}
//line stdlib/url/url.kuki:185
	return kukistring.HasPrefix(cleanCand, trimmedBase+"/")
}

//line stdlib/url/url.kuki:191
func EncodeForm(values map[string]string) string {
//line stdlib/url/url.kuki:192
	if len(values) == 0 {
//line stdlib/url/url.kuki:193
		return ""
	}
//line stdlib/url/url.kuki:195
	keys := make([]string, 0, len(values))
//line stdlib/url/url.kuki:196
	for k := range values {
//line stdlib/url/url.kuki:197
		keys = append(keys, k)
	}
//line stdlib/url/url.kuki:198
	keys = sort.Strings(keys)
//line stdlib/url/url.kuki:200
	parts := make([]string, 0, len(keys))
//line stdlib/url/url.kuki:201
	for _, k := range keys {
//line stdlib/url/url.kuki:202
		parts = append(parts, gourl.QueryEscape(k)+"="+gourl.QueryEscape(values[k]))
	}
//line stdlib/url/url.kuki:203
	return kukistring.Join(parts, "&")
}
